namespace Aisino.Fwkp.Wbjk.Forms
{
    using Aisino.Framework.Plugin.Core.Controls;
    using Aisino.Fwkp.Wbjk.Properties;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class XSDJEdite2 : DockForm
    {
        private Button button1;
        private AisinoCHK checkBox_GF;
        private AisinoCHK checkBox_HYSY;
        private AisinoCHK checkBox_SFZJY;
        private AisinoCHK checkBox_XF;
        public AisinoMultiCombox com_fhr;
        public AisinoMultiCombox com_gfdzdh;
        public AisinoMultiCombox com_gfmc;
        public AisinoMultiCombox com_gfsbh;
        public AisinoMultiCombox com_gfzh;
        public AisinoMultiCombox com_skr;
        public AisinoMultiCombox com_xfdzdh;
        public AisinoMultiCombox com_xfmc;
        public AisinoMultiCombox com_xfsbh;
        public AisinoMultiCombox com_xfyhzh;
        private AisinoCMB comboBoxDJZL;
        private IContainer components = null;
        private DateTimePicker dateTimePicker1;
        public DataGridView dgv_spmx;
        public AisinoLBL lab_Amount;
        private AisinoLBL lab_bz;
        private AisinoLBL lab_DJZT;
        private AisinoLBL lab_hj_jshj_dx;
        public AisinoLBL lab_hj_xx;
        private AisinoLBL lab_KPZT;
        public AisinoLBL lab_Tax;
        public AisinoLBL lab_title;
        private AisinoLBL label10;
        private AisinoLBL label11;
        private AisinoLBL label12;
        private AisinoLBL label13;
        private AisinoLBL label17;
        private AisinoLBL label18;
        private AisinoLBL label19;
        private AisinoLBL label2;
        private AisinoLBL label20;
        private AisinoLBL label21;
        private AisinoLBL label23;
        private AisinoLBL label26;
        private AisinoLBL label27;
        private AisinoLBL label29;
        private AisinoLBL label31;
        private AisinoLBL label32;
        private AisinoLBL label7;
        private AisinoLBL label8;
        private AisinoLBL label9;
        private AisinoLBL labelDJH;
        private AisinoLBL labelDJRQ;
        private AisinoLBL labelDJZL;
        private AisinoLBL labelQD;
        private AisinoTXT textBoxDJH;
        private AisinoTXT textBoxQDSPHMX;
        private ToolStrip toolbtnBuQi;
        private ToolStripButton toolBtnCheck;
        private ToolStripButton toolStripBtnCancel;
        private ToolStripButton toolStripBtnHSJG;
        private ToolStripButton toolStripBtnSave;
        private ToolStripButton toolStripButtonAdd;
        private ToolStripButton toolStripButtonDel;
        private ToolStripButton toolStripButtonKH;
        private ToolStripButton toolStripButtonZK;
        public AisinoTXT txt_bz;
        private XmlComponentLoader xmlComponentLoader1;

        public XSDJEdite2()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void Initialize()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            this.toolBtnCheck = new ToolStripButton();
            this.toolStripButtonZK = new ToolStripButton();
            this.toolStripBtnHSJG = new ToolStripButton();
            this.button1 = new Button();
            this.toolStripButtonKH = new ToolStripButton();
            this.lab_hj_xx = new AisinoLBL();
            this.label2 = new AisinoLBL();
            this.toolStripButtonDel = new ToolStripButton();
            this.com_skr = new AisinoMultiCombox();
            this.com_fhr = new AisinoMultiCombox();
            this.com_gfzh = new AisinoMultiCombox();
            this.com_gfsbh = new AisinoMultiCombox();
            this.com_xfyhzh = new AisinoMultiCombox();
            this.com_xfdzdh = new AisinoMultiCombox();
            this.com_xfsbh = new AisinoMultiCombox();
            this.com_xfmc = new AisinoMultiCombox();
            this.com_gfdzdh = new AisinoMultiCombox();
            this.com_gfmc = new AisinoMultiCombox();
            this.label17 = new AisinoLBL();
            this.label31 = new AisinoLBL();
            this.label32 = new AisinoLBL();
            this.label29 = new AisinoLBL();
            this.label23 = new AisinoLBL();
            this.label7 = new AisinoLBL();
            this.lab_Tax = new AisinoLBL();
            this.lab_Amount = new AisinoLBL();
            this.label12 = new AisinoLBL();
            this.dgv_spmx = new DataGridView();
            this.txt_bz = new AisinoTXT();
            this.lab_title = new AisinoLBL();
            this.lab_DJZT = new AisinoLBL();
            this.lab_hj_jshj_dx = new AisinoLBL();
            this.toolStripButtonAdd = new ToolStripButton();
            this.lab_bz = new AisinoLBL();
            this.lab_KPZT = new AisinoLBL();
            this.label27 = new AisinoLBL();
            this.label26 = new AisinoLBL();
            this.label21 = new AisinoLBL();
            this.label20 = new AisinoLBL();
            this.label19 = new AisinoLBL();
            this.label18 = new AisinoLBL();
            this.label13 = new AisinoLBL();
            this.label8 = new AisinoLBL();
            this.label9 = new AisinoLBL();
            this.label10 = new AisinoLBL();
            this.label11 = new AisinoLBL();
            this.dateTimePicker1 = new DateTimePicker();
            this.toolStripBtnCancel = new ToolStripButton();
            this.labelDJRQ = new AisinoLBL();
            this.textBoxQDSPHMX = new AisinoTXT();
            this.checkBox_HYSY = new AisinoCHK();
            this.checkBox_SFZJY = new AisinoCHK();
            this.toolStripBtnSave = new ToolStripButton();
            this.checkBox_XF = new AisinoCHK();
            this.checkBox_GF = new AisinoCHK();
            this.textBoxDJH = new AisinoTXT();
            this.labelDJH = new AisinoLBL();
            this.comboBoxDJZL = new AisinoCMB();
            this.labelDJZL = new AisinoLBL();
            this.labelQD = new AisinoLBL();
            this.toolbtnBuQi = new ToolStrip();
            ((ISupportInitialize) this.dgv_spmx).BeginInit();
            this.toolbtnBuQi.SuspendLayout();
            this.toolBtnCheck.Image = Resources.修改;
            this.toolBtnCheck.ImageScaling = ToolStripItemImageScaling.None;
            this.toolBtnCheck.ImageTransparentColor = Color.Magenta;
            this.toolBtnCheck.Name = "toolBtnCheck";
            this.toolBtnCheck.Size = new Size(0x34, 0x16);
            this.toolBtnCheck.Text = "检查";
            this.toolStripButtonZK.Image = Resources.折扣;
            this.toolStripButtonZK.ImageScaling = ToolStripItemImageScaling.None;
            this.toolStripButtonZK.ImageTransparentColor = Color.Magenta;
            this.toolStripButtonZK.Name = "toolStripButtonZK";
            this.toolStripButtonZK.Size = new Size(0x4c, 0x16);
            this.toolStripButtonZK.Text = "添加折扣";
            this.toolStripBtnHSJG.Image = Resources.含税;
            this.toolStripBtnHSJG.ImageScaling = ToolStripItemImageScaling.None;
            this.toolStripBtnHSJG.ImageTransparentColor = Color.Magenta;
            this.toolStripBtnHSJG.Name = "toolStripBtnHSJG";
            this.toolStripBtnHSJG.Size = new Size(0x4c, 0x16);
            this.toolStripBtnHSJG.Text = "含税价格";
            this.button1.Location = new Point(600, 0x2c);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x4b, 0x17);
            this.button1.TabIndex = 0x13c;
            this.button1.Text = "button1";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Visible = false;
            this.toolStripButtonKH.ImageScaling = ToolStripItemImageScaling.None;
            this.toolStripButtonKH.ImageTransparentColor = Color.Magenta;
            this.toolStripButtonKH.Name = "toolStripButtonKH";
            this.toolStripButtonKH.Size = new Size(60, 0x16);
            this.toolStripButtonKH.Text = "添加客户";
            this.lab_hj_xx.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.lab_hj_xx.AutoSize = true;
            this.lab_hj_xx.BackColor = SystemColors.ControlLightLight;
            this.lab_hj_xx.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_hj_xx.Location = new Point(0x2eb, 470);
            this.lab_hj_xx.Name = "lab_hj_xx";
            this.lab_hj_xx.Size = new Size(11, 12);
            this.lab_hj_xx.TabIndex = 0x130;
            this.lab_hj_xx.Text = "0";
            this.label2.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.label2.AutoSize = true;
            this.label2.BackColor = SystemColors.ControlLightLight;
            this.label2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label2.Location = new Point(0x298, 0x1d4);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x33, 15);
            this.label2.TabIndex = 0x12f;
            this.label2.Text = "(小写)：";
            this.toolStripButtonDel.Image = Resources.减;
            this.toolStripButtonDel.ImageScaling = ToolStripItemImageScaling.None;
            this.toolStripButtonDel.ImageTransparentColor = Color.Magenta;
            this.toolStripButtonDel.Name = "toolStripButtonDel";
            this.toolStripButtonDel.Size = new Size(0x34, 0x16);
            this.toolStripButtonDel.Text = "删除";
            this.com_skr.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_skr.set_AutoComplate(0);
            this.com_skr.set_AutoIndex(1);
            this.com_skr.set_BorderColor(SystemColors.Control);
            this.com_skr.set_BorderStyle(1);
            this.com_skr.set_ButtonAutoHide(true);
            this.com_skr.set_buttonStyle(1);
            this.com_skr.set_DataSource(null);
            this.com_skr.set_DrawHead(false);
            this.com_skr.set_Edit(1);
            this.com_skr.set_IsSelectAll(false);
            this.com_skr.Location = new Point(0x7e, 0x250);
            this.com_skr.set_MaxIndex(8);
            this.com_skr.set_MaxLength(0x7fff);
            this.com_skr.Name = "com_skr";
            this.com_skr.set_ReadOnly(false);
            this.com_skr.set_SelectedIndex(-1);
            this.com_skr.set_SelectionStart(0);
            this.com_skr.set_ShowText("");
            this.com_skr.Size = new Size(0x45, 0x15);
            this.com_skr.TabIndex = 0x119;
            this.com_skr.set_UnderLineColor(Color.Transparent);
            this.com_skr.set_UnderLineStyle(0);
            this.com_fhr.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_fhr.set_AutoComplate(0);
            this.com_fhr.set_AutoIndex(1);
            this.com_fhr.set_BorderColor(SystemColors.Control);
            this.com_fhr.set_BorderStyle(1);
            this.com_fhr.set_ButtonAutoHide(true);
            this.com_fhr.set_buttonStyle(1);
            this.com_fhr.set_DataSource(null);
            this.com_fhr.set_DrawHead(false);
            this.com_fhr.set_Edit(1);
            this.com_fhr.set_IsSelectAll(false);
            this.com_fhr.Location = new Point(0x15b, 0x250);
            this.com_fhr.set_MaxIndex(8);
            this.com_fhr.set_MaxLength(0x7fff);
            this.com_fhr.Name = "com_fhr";
            this.com_fhr.set_ReadOnly(false);
            this.com_fhr.set_SelectedIndex(-1);
            this.com_fhr.set_SelectionStart(0);
            this.com_fhr.set_ShowText("");
            this.com_fhr.Size = new Size(0x45, 0x15);
            this.com_fhr.TabIndex = 0x11a;
            this.com_fhr.set_UnderLineColor(Color.Transparent);
            this.com_fhr.set_UnderLineStyle(0);
            this.com_gfzh.set_AutoComplate(0);
            this.com_gfzh.set_AutoIndex(1);
            this.com_gfzh.set_BorderColor(SystemColors.Control);
            this.com_gfzh.set_BorderStyle(1);
            this.com_gfzh.set_ButtonAutoHide(true);
            this.com_gfzh.set_buttonStyle(1);
            this.com_gfzh.set_DataSource(null);
            this.com_gfzh.set_DrawHead(true);
            this.com_gfzh.set_Edit(1);
            this.com_gfzh.set_IsSelectAll(false);
            this.com_gfzh.Location = new Point(0xc5, 0xbd);
            this.com_gfzh.set_MaxIndex(8);
            this.com_gfzh.set_MaxLength(0x7fff);
            this.com_gfzh.Name = "com_gfzh";
            this.com_gfzh.set_ReadOnly(false);
            this.com_gfzh.set_SelectedIndex(-1);
            this.com_gfzh.set_SelectionStart(0);
            this.com_gfzh.set_ShowText("");
            this.com_gfzh.Size = new Size(0x160, 0x15);
            this.com_gfzh.TabIndex = 0x113;
            this.com_gfzh.set_UnderLineColor(Color.Transparent);
            this.com_gfzh.set_UnderLineStyle(1);
            this.com_gfsbh.set_AutoComplate(0);
            this.com_gfsbh.set_AutoIndex(1);
            this.com_gfsbh.set_BorderColor(SystemColors.Control);
            this.com_gfsbh.set_BorderStyle(1);
            this.com_gfsbh.set_ButtonAutoHide(true);
            this.com_gfsbh.set_buttonStyle(1);
            this.com_gfsbh.set_DataSource(null);
            this.com_gfsbh.set_DrawHead(true);
            this.com_gfsbh.set_Edit(1);
            this.com_gfsbh.set_IsSelectAll(false);
            this.com_gfsbh.Location = new Point(0xc5, 0x8f);
            this.com_gfsbh.set_MaxIndex(8);
            this.com_gfsbh.set_MaxLength(0x7fff);
            this.com_gfsbh.Name = "com_gfsbh";
            this.com_gfsbh.set_ReadOnly(false);
            this.com_gfsbh.set_SelectedIndex(-1);
            this.com_gfsbh.set_SelectionStart(0);
            this.com_gfsbh.set_ShowText("");
            this.com_gfsbh.Size = new Size(0x160, 0x15);
            this.com_gfsbh.TabIndex = 0x111;
            this.com_gfsbh.set_UnderLineColor(Color.Transparent);
            this.com_gfsbh.set_UnderLineStyle(1);
            this.com_xfyhzh.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_xfyhzh.set_AutoComplate(0);
            this.com_xfyhzh.set_AutoIndex(1);
            this.com_xfyhzh.set_BorderColor(SystemColors.Control);
            this.com_xfyhzh.set_BorderStyle(1);
            this.com_xfyhzh.set_ButtonAutoHide(true);
            this.com_xfyhzh.set_buttonStyle(1);
            this.com_xfyhzh.set_DataSource(null);
            this.com_xfyhzh.set_DrawHead(false);
            this.com_xfyhzh.set_Edit(1);
            this.com_xfyhzh.set_IsSelectAll(false);
            this.com_xfyhzh.Location = new Point(0xbc, 0x231);
            this.com_xfyhzh.set_MaxIndex(8);
            this.com_xfyhzh.set_MaxLength(0x7fff);
            this.com_xfyhzh.Name = "com_xfyhzh";
            this.com_xfyhzh.set_ReadOnly(false);
            this.com_xfyhzh.set_SelectedIndex(-1);
            this.com_xfyhzh.set_SelectionStart(0);
            this.com_xfyhzh.set_ShowText("");
            this.com_xfyhzh.Size = new Size(0x169, 0x15);
            this.com_xfyhzh.TabIndex = 280;
            this.com_xfyhzh.set_UnderLineColor(Color.Transparent);
            this.com_xfyhzh.set_UnderLineStyle(1);
            this.com_xfdzdh.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_xfdzdh.set_AutoComplate(0);
            this.com_xfdzdh.set_AutoIndex(1);
            this.com_xfdzdh.set_BorderColor(SystemColors.Control);
            this.com_xfdzdh.set_BorderStyle(1);
            this.com_xfdzdh.set_ButtonAutoHide(true);
            this.com_xfdzdh.set_buttonStyle(1);
            this.com_xfdzdh.set_DataSource(null);
            this.com_xfdzdh.set_DrawHead(false);
            this.com_xfdzdh.set_Edit(1);
            this.com_xfdzdh.set_IsSelectAll(false);
            this.com_xfdzdh.Location = new Point(0xbc, 0x21a);
            this.com_xfdzdh.set_MaxIndex(8);
            this.com_xfdzdh.set_MaxLength(0x7fff);
            this.com_xfdzdh.Name = "com_xfdzdh";
            this.com_xfdzdh.set_ReadOnly(false);
            this.com_xfdzdh.set_SelectedIndex(-1);
            this.com_xfdzdh.set_SelectionStart(0);
            this.com_xfdzdh.set_ShowText("");
            this.com_xfdzdh.Size = new Size(0x169, 0x15);
            this.com_xfdzdh.TabIndex = 0x117;
            this.com_xfdzdh.set_UnderLineColor(Color.Transparent);
            this.com_xfdzdh.set_UnderLineStyle(1);
            this.com_xfsbh.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_xfsbh.set_AutoComplate(0);
            this.com_xfsbh.set_AutoIndex(1);
            this.com_xfsbh.set_BorderColor(SystemColors.Control);
            this.com_xfsbh.set_BorderStyle(1);
            this.com_xfsbh.set_ButtonAutoHide(true);
            this.com_xfsbh.set_buttonStyle(1);
            this.com_xfsbh.set_DataSource(null);
            this.com_xfsbh.set_DrawHead(true);
            this.com_xfsbh.set_Edit(1);
            this.com_xfsbh.set_IsSelectAll(false);
            this.com_xfsbh.Location = new Point(0xbc, 0x203);
            this.com_xfsbh.set_MaxIndex(8);
            this.com_xfsbh.set_MaxLength(0x7fff);
            this.com_xfsbh.Name = "com_xfsbh";
            this.com_xfsbh.set_ReadOnly(false);
            this.com_xfsbh.set_SelectedIndex(-1);
            this.com_xfsbh.set_SelectionStart(0);
            this.com_xfsbh.set_ShowText("");
            this.com_xfsbh.Size = new Size(0x169, 0x15);
            this.com_xfsbh.TabIndex = 0x116;
            this.com_xfsbh.set_UnderLineColor(Color.Transparent);
            this.com_xfsbh.set_UnderLineStyle(1);
            this.com_xfmc.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_xfmc.set_AutoComplate(0);
            this.com_xfmc.set_AutoIndex(1);
            this.com_xfmc.set_BorderColor(SystemColors.Control);
            this.com_xfmc.set_BorderStyle(1);
            this.com_xfmc.set_ButtonAutoHide(true);
            this.com_xfmc.set_buttonStyle(1);
            this.com_xfmc.set_DataSource(null);
            this.com_xfmc.set_DrawHead(true);
            this.com_xfmc.set_Edit(1);
            this.com_xfmc.set_IsSelectAll(false);
            this.com_xfmc.Location = new Point(0xbc, 0x1ec);
            this.com_xfmc.set_MaxIndex(8);
            this.com_xfmc.set_MaxLength(0x7fff);
            this.com_xfmc.Name = "com_xfmc";
            this.com_xfmc.set_ReadOnly(false);
            this.com_xfmc.set_SelectedIndex(-1);
            this.com_xfmc.set_SelectionStart(0);
            this.com_xfmc.set_ShowText("");
            this.com_xfmc.Size = new Size(0x169, 0x15);
            this.com_xfmc.TabIndex = 0x115;
            this.com_xfmc.set_UnderLineColor(Color.Transparent);
            this.com_xfmc.set_UnderLineStyle(1);
            this.com_gfdzdh.set_AutoComplate(0);
            this.com_gfdzdh.set_AutoIndex(1);
            this.com_gfdzdh.set_BorderColor(SystemColors.Control);
            this.com_gfdzdh.set_BorderStyle(1);
            this.com_gfdzdh.set_ButtonAutoHide(true);
            this.com_gfdzdh.set_buttonStyle(1);
            this.com_gfdzdh.set_DataSource(null);
            this.com_gfdzdh.set_DrawHead(true);
            this.com_gfdzdh.set_Edit(1);
            this.com_gfdzdh.set_IsSelectAll(false);
            this.com_gfdzdh.Location = new Point(0xc5, 0xa6);
            this.com_gfdzdh.set_MaxIndex(8);
            this.com_gfdzdh.set_MaxLength(0x7fff);
            this.com_gfdzdh.Name = "com_gfdzdh";
            this.com_gfdzdh.set_ReadOnly(false);
            this.com_gfdzdh.set_SelectedIndex(-1);
            this.com_gfdzdh.set_SelectionStart(0);
            this.com_gfdzdh.set_ShowText("");
            this.com_gfdzdh.Size = new Size(0x160, 0x15);
            this.com_gfdzdh.TabIndex = 0x112;
            this.com_gfdzdh.set_UnderLineColor(Color.Transparent);
            this.com_gfdzdh.set_UnderLineStyle(1);
            this.com_gfmc.set_AutoComplate(0);
            this.com_gfmc.set_AutoIndex(1);
            this.com_gfmc.set_BorderColor(SystemColors.Control);
            this.com_gfmc.set_BorderStyle(1);
            this.com_gfmc.set_ButtonAutoHide(true);
            this.com_gfmc.set_buttonStyle(1);
            this.com_gfmc.set_DataSource(null);
            this.com_gfmc.set_DrawHead(true);
            this.com_gfmc.set_Edit(1);
            this.com_gfmc.ForeColor = Color.Black;
            this.com_gfmc.set_IsSelectAll(false);
            this.com_gfmc.Location = new Point(0xc5, 120);
            this.com_gfmc.set_MaxIndex(8);
            this.com_gfmc.set_MaxLength(0x7fff);
            this.com_gfmc.Name = "com_gfmc";
            this.com_gfmc.set_ReadOnly(false);
            this.com_gfmc.set_SelectedIndex(-1);
            this.com_gfmc.set_SelectionStart(0);
            this.com_gfmc.set_ShowText("");
            this.com_gfmc.Size = new Size(0x160, 0x15);
            this.com_gfmc.TabIndex = 0x110;
            this.com_gfmc.set_UnderLineColor(Color.Transparent);
            this.com_gfmc.set_UnderLineStyle(1);
            this.label17.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label17.AutoSize = true;
            this.label17.BackColor = SystemColors.ButtonHighlight;
            this.label17.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label17.Location = new Point(0x44, 0x1ec);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x13, 15);
            this.label17.TabIndex = 0x131;
            this.label17.Text = "销";
            this.label31.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label31.AutoSize = true;
            this.label31.BackColor = SystemColors.ButtonHighlight;
            this.label31.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label31.Location = new Point(0x44, 0x232);
            this.label31.Name = "label31";
            this.label31.Size = new Size(0x13, 15);
            this.label31.TabIndex = 310;
            this.label31.Text = "方";
            this.label32.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label32.AutoSize = true;
            this.label32.BackColor = SystemColors.ButtonHighlight;
            this.label32.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label32.Location = new Point(0x44, 0x20e);
            this.label32.Name = "label32";
            this.label32.Size = new Size(0x13, 15);
            this.label32.TabIndex = 0x134;
            this.label32.Text = "售";
            this.label29.AutoSize = true;
            this.label29.BackColor = SystemColors.ButtonHighlight;
            this.label29.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label29.Location = new Point(0x42, 0xc0);
            this.label29.Name = "label29";
            this.label29.Size = new Size(0x13, 15);
            this.label29.TabIndex = 0x128;
            this.label29.Text = "方";
            this.label23.AutoSize = true;
            this.label23.BackColor = SystemColors.ButtonHighlight;
            this.label23.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label23.Location = new Point(0x42, 0x9c);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x13, 15);
            this.label23.TabIndex = 0x125;
            this.label23.Text = "买";
            this.label7.AutoSize = true;
            this.label7.BackColor = SystemColors.ButtonHighlight;
            this.label7.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label7.Location = new Point(0x42, 120);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x13, 15);
            this.label7.TabIndex = 0x123;
            this.label7.Text = "购";
            this.lab_Tax.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.lab_Tax.AutoSize = true;
            this.lab_Tax.BackColor = SystemColors.ControlLightLight;
            this.lab_Tax.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_Tax.Location = new Point(0x307, 0x1be);
            this.lab_Tax.Name = "lab_Tax";
            this.lab_Tax.Size = new Size(0x29, 12);
            this.lab_Tax.TabIndex = 300;
            this.lab_Tax.Text = "税额：";
            this.lab_Amount.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.lab_Amount.AutoSize = true;
            this.lab_Amount.BackColor = SystemColors.ControlLightLight;
            this.lab_Amount.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_Amount.Location = new Point(0x215, 0x1be);
            this.lab_Amount.Name = "lab_Amount";
            this.lab_Amount.Size = new Size(0x29, 12);
            this.lab_Amount.TabIndex = 0x12b;
            this.lab_Amount.Text = "金额：";
            this.label12.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label12.AutoSize = true;
            this.label12.BackColor = SystemColors.ControlLightLight;
            this.label12.Font = new Font("Microsoft Sans Serif", 9f);
            this.label12.Location = new Point(0x5f, 0x1bc);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x31, 15);
            this.label12.TabIndex = 0x12a;
            this.label12.Text = "合      计";
            this.dgv_spmx.AllowUserToAddRows = false;
            this.dgv_spmx.AllowUserToOrderColumns = true;
            this.dgv_spmx.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.dgv_spmx.BackgroundColor = SystemColors.ButtonHighlight;
            style.Alignment = DataGridViewContentAlignment.MiddleCenter;
            style.BackColor = SystemColors.Control;
            style.Font = new Font("Microsoft Sans Serif", 9f);
            style.ForeColor = SystemColors.WindowText;
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.False;
            this.dgv_spmx.ColumnHeadersDefaultCellStyle = style;
            this.dgv_spmx.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_spmx.GridColor = Color.Gray;
            this.dgv_spmx.Location = new Point(0x42, 220);
            this.dgv_spmx.Name = "dgv_spmx";
            this.dgv_spmx.ReadOnly = true;
            this.dgv_spmx.RowHeadersVisible = false;
            this.dgv_spmx.RowTemplate.Height = 0x17;
            this.dgv_spmx.SelectionMode = DataGridViewSelectionMode.CellSelect;
            this.dgv_spmx.Size = new Size(0x393, 0xdf);
            this.dgv_spmx.TabIndex = 0x114;
            this.txt_bz.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.txt_bz.BorderStyle = BorderStyle.None;
            this.txt_bz.Location = new Point(0x24a, 0x1f2);
            this.txt_bz.Multiline = true;
            this.txt_bz.Name = "txt_bz";
            this.txt_bz.Size = new Size(0x146, 0x54);
            this.txt_bz.TabIndex = 0x11b;
            this.lab_title.Anchor = AnchorStyles.Top;
            this.lab_title.AutoSize = true;
            this.lab_title.BackColor = SystemColors.ControlLightLight;
            this.lab_title.Font = new Font("Microsoft Sans Serif", 14f, FontStyle.Bold);
            this.lab_title.ForeColor = Color.Blue;
            this.lab_title.Location = new Point(0x1b9, 0x25);
            this.lab_title.Name = "lab_title";
            this.lab_title.Size = new Size(0x60, 0x18);
            this.lab_title.TabIndex = 290;
            this.lab_title.Text = "销售单据.";
            this.lab_DJZT.AutoSize = true;
            this.lab_DJZT.BackColor = SystemColors.ControlLightLight;
            this.lab_DJZT.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.lab_DJZT.Location = new Point(0x44, 0x41);
            this.lab_DJZT.Name = "lab_DJZT";
            this.lab_DJZT.Size = new Size(0x39, 12);
            this.lab_DJZT.TabIndex = 0x11c;
            this.lab_DJZT.Text = "单据状态";
            this.lab_hj_jshj_dx.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.lab_hj_jshj_dx.AutoSize = true;
            this.lab_hj_jshj_dx.BackColor = SystemColors.ControlLightLight;
            this.lab_hj_jshj_dx.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_hj_jshj_dx.Location = new Point(0x15f, 0x1d4);
            this.lab_hj_jshj_dx.Name = "lab_hj_jshj_dx";
            this.lab_hj_jshj_dx.Size = new Size(0x11, 12);
            this.lab_hj_jshj_dx.TabIndex = 0x12e;
            this.lab_hj_jshj_dx.Text = "零";
            this.toolStripButtonAdd.Image = Resources.加入;
            this.toolStripButtonAdd.ImageScaling = ToolStripItemImageScaling.None;
            this.toolStripButtonAdd.ImageTransparentColor = Color.Magenta;
            this.toolStripButtonAdd.Name = "toolStripButtonAdd";
            this.toolStripButtonAdd.Size = new Size(0x34, 0x16);
            this.toolStripButtonAdd.Text = "增加";
            this.lab_bz.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.lab_bz.AutoSize = true;
            this.lab_bz.BackColor = SystemColors.ControlLightLight;
            this.lab_bz.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_bz.Location = new Point(0x22b, 0x1f8);
            this.lab_bz.Name = "lab_bz";
            this.lab_bz.Size = new Size(0x13, 90);
            this.lab_bz.TabIndex = 0x133;
            this.lab_bz.Text = "备\r\n\r\n\r\n\r\n\r\n注";
            this.lab_KPZT.AutoSize = true;
            this.lab_KPZT.BackColor = SystemColors.ControlLightLight;
            this.lab_KPZT.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.lab_KPZT.Location = new Point(0x44, 0x2c);
            this.lab_KPZT.Name = "lab_KPZT";
            this.lab_KPZT.Size = new Size(0x39, 12);
            this.lab_KPZT.TabIndex = 0x13b;
            this.lab_KPZT.Text = "开票状态";
            this.label27.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label27.AutoSize = true;
            this.label27.BackColor = SystemColors.ControlLightLight;
            this.label27.Font = new Font("Microsoft Sans Serif", 9f);
            this.label27.Location = new Point(0x126, 0x254);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x2b, 15);
            this.label27.TabIndex = 0x13a;
            this.label27.Text = "复核：";
            this.label26.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label26.AutoSize = true;
            this.label26.BackColor = SystemColors.ControlLightLight;
            this.label26.Font = new Font("Microsoft Sans Serif", 9f);
            this.label26.Location = new Point(0x44, 0x253);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x37, 15);
            this.label26.TabIndex = 0x139;
            this.label26.Text = "收款人：";
            this.label21.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label21.AutoSize = true;
            this.label21.BackColor = SystemColors.ControlLightLight;
            this.label21.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label21.Location = new Point(0x5f, 0x234);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x5b, 15);
            this.label21.TabIndex = 0x138;
            this.label21.Text = "开户行及账号：";
            this.label20.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label20.AutoSize = true;
            this.label20.BackColor = SystemColors.ControlLightLight;
            this.label20.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label20.Location = new Point(0x5f, 540);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x5b, 15);
            this.label20.TabIndex = 0x137;
            this.label20.Text = "地 址 、 电 话：";
            this.label19.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label19.AutoSize = true;
            this.label19.BackColor = SystemColors.ControlLightLight;
            this.label19.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label19.Location = new Point(0x5f, 0x204);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x5b, 15);
            this.label19.TabIndex = 0x135;
            this.label19.Text = "纳税人识别号：";
            this.label18.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label18.AutoSize = true;
            this.label18.BackColor = SystemColors.ControlLightLight;
            this.label18.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label18.Location = new Point(0x5f, 0x1ec);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x5b, 15);
            this.label18.TabIndex = 0x132;
            this.label18.Text = "名                称：";
            this.label13.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label13.AutoSize = true;
            this.label13.BackColor = SystemColors.ControlLightLight;
            this.label13.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label13.Location = new Point(0x5b, 0x1d2);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x63, 15);
            this.label13.TabIndex = 0x12d;
            this.label13.Text = "价税合计(大写)：";
            this.label8.AutoSize = true;
            this.label8.BackColor = SystemColors.ControlLightLight;
            this.label8.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label8.Location = new Point(0x5f, 120);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x5b, 15);
            this.label8.TabIndex = 0x124;
            this.label8.Text = "名                称：";
            this.label9.AutoSize = true;
            this.label9.BackColor = SystemColors.ControlLightLight;
            this.label9.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label9.Location = new Point(0x5f, 0x90);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x5b, 15);
            this.label9.TabIndex = 0x126;
            this.label9.Text = "纳税人识别号：";
            this.label10.AutoSize = true;
            this.label10.BackColor = SystemColors.ControlLightLight;
            this.label10.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label10.Location = new Point(0x5f, 0xa8);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x5b, 15);
            this.label10.TabIndex = 0x127;
            this.label10.Text = "地 址 、 电 话：";
            this.label11.AutoSize = true;
            this.label11.BackColor = SystemColors.ControlLightLight;
            this.label11.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label11.Location = new Point(0x5f, 0xc0);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x5b, 15);
            this.label11.TabIndex = 0x129;
            this.label11.Text = "开户行及账号：";
            this.dateTimePicker1.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.dateTimePicker1.Location = new Point(0x367, 0x59);
            this.dateTimePicker1.Name = "dateTimePicker1";
            this.dateTimePicker1.Size = new Size(0x6a, 0x15);
            this.dateTimePicker1.TabIndex = 0x10b;
            this.toolStripBtnCancel.Image = Resources.退出;
            this.toolStripBtnCancel.ImageScaling = ToolStripItemImageScaling.None;
            this.toolStripBtnCancel.ImageTransparentColor = Color.Magenta;
            this.toolStripBtnCancel.Name = "toolStripBtnCancel";
            this.toolStripBtnCancel.Size = new Size(0x34, 0x16);
            this.toolStripBtnCancel.Text = "退出";
            this.labelDJRQ.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.labelDJRQ.AutoSize = true;
            this.labelDJRQ.BackColor = SystemColors.ButtonHighlight;
            this.labelDJRQ.Location = new Point(0x32c, 0x5d);
            this.labelDJRQ.Name = "labelDJRQ";
            this.labelDJRQ.Size = new Size(0x35, 12);
            this.labelDJRQ.TabIndex = 0x121;
            this.labelDJRQ.Text = "单据日期";
            this.textBoxQDSPHMX.Location = new Point(0x243, 0x59);
            this.textBoxQDSPHMX.Name = "textBoxQDSPHMX";
            this.textBoxQDSPHMX.Size = new Size(0xb3, 0x15);
            this.textBoxQDSPHMX.TabIndex = 0x10a;
            this.checkBox_HYSY.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.checkBox_HYSY.AutoSize = true;
            this.checkBox_HYSY.BackColor = SystemColors.ButtonHighlight;
            this.checkBox_HYSY.Location = new Point(0x2ba, 0x7d);
            this.checkBox_HYSY.Name = "checkBox_HYSY";
            this.checkBox_HYSY.Size = new Size(0x48, 0x10);
            this.checkBox_HYSY.TabIndex = 0x10d;
            this.checkBox_HYSY.Text = "中外合作油气田";
            this.checkBox_HYSY.UseVisualStyleBackColor = false;
            this.checkBox_SFZJY.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.checkBox_SFZJY.AutoSize = true;
            this.checkBox_SFZJY.BackColor = SystemColors.ButtonHighlight;
            this.checkBox_SFZJY.Location = new Point(0x315, 0x7d);
            this.checkBox_SFZJY.Name = "checkBox_SFZJY";
            this.checkBox_SFZJY.Size = new Size(0x54, 0x10);
            this.checkBox_SFZJY.TabIndex = 0x10f;
            this.checkBox_SFZJY.Text = "身份证校验";
            this.checkBox_SFZJY.UseVisualStyleBackColor = false;
            this.toolStripBtnSave.Image = Resources.修改;
            this.toolStripBtnSave.ImageScaling = ToolStripItemImageScaling.None;
            this.toolStripBtnSave.ImageTransparentColor = Color.Magenta;
            this.toolStripBtnSave.Name = "toolStripBtnSave";
            this.toolStripBtnSave.Size = new Size(0x34, 0x16);
            this.toolStripBtnSave.Text = "保存";
            this.checkBox_XF.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.checkBox_XF.AutoSize = true;
            this.checkBox_XF.BackColor = SystemColors.ButtonHighlight;
            this.checkBox_XF.Location = new Point(0x2ba, 150);
            this.checkBox_XF.Name = "checkBox_XF";
            this.checkBox_XF.Size = new Size(0x60, 0x10);
            this.checkBox_XF.TabIndex = 0x10c;
            this.checkBox_XF.Text = "农产品销售方";
            this.checkBox_XF.UseVisualStyleBackColor = false;
            this.checkBox_GF.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.checkBox_GF.AutoSize = true;
            this.checkBox_GF.BackColor = SystemColors.ButtonHighlight;
            this.checkBox_GF.Location = new Point(0x2ba, 0xaf);
            this.checkBox_GF.Name = "checkBox_GF";
            this.checkBox_GF.Size = new Size(0x60, 0x10);
            this.checkBox_GF.TabIndex = 270;
            this.checkBox_GF.Text = "农产品收购方";
            this.checkBox_GF.UseVisualStyleBackColor = false;
            this.textBoxDJH.Cursor = Cursors.IBeam;
            this.textBoxDJH.ForeColor = SystemColors.WindowText;
            this.textBoxDJH.Location = new Point(0x129, 0x59);
            this.textBoxDJH.Name = "textBoxDJH";
            this.textBoxDJH.Size = new Size(0xab, 0x15);
            this.textBoxDJH.TabIndex = 0x109;
            this.labelDJH.AutoSize = true;
            this.labelDJH.BackColor = SystemColors.ButtonHighlight;
            this.labelDJH.Location = new Point(0xf8, 0x5d);
            this.labelDJH.Name = "labelDJH";
            this.labelDJH.Size = new Size(0x29, 12);
            this.labelDJH.TabIndex = 0x120;
            this.labelDJH.Text = "单据号";
            this.comboBoxDJZL.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBoxDJZL.FormattingEnabled = true;
            this.comboBoxDJZL.Location = new Point(0x81, 0x59);
            this.comboBoxDJZL.Name = "comboBoxDJZL";
            this.comboBoxDJZL.Size = new Size(0x63, 20);
            this.comboBoxDJZL.TabIndex = 0x108;
            this.labelDJZL.AutoSize = true;
            this.labelDJZL.BackColor = SystemColors.ButtonHighlight;
            this.labelDJZL.Location = new Point(0x41, 0x5d);
            this.labelDJZL.Name = "labelDJZL";
            this.labelDJZL.Size = new Size(0x35, 12);
            this.labelDJZL.TabIndex = 0x11f;
            this.labelDJZL.Text = "单据种类";
            this.labelQD.AutoSize = true;
            this.labelQD.BackColor = SystemColors.ButtonHighlight;
            this.labelQD.Location = new Point(0x1e4, 0x5d);
            this.labelQD.Name = "labelQD";
            this.labelQD.Size = new Size(0x59, 12);
            this.labelQD.TabIndex = 0x11e;
            this.labelQD.Text = "清单行商品名称";
            this.toolbtnBuQi.AutoSize = false;
            this.toolbtnBuQi.Items.AddRange(new ToolStripItem[] { this.toolStripBtnCancel, this.toolStripBtnSave, this.toolStripButtonAdd, this.toolStripButtonDel, this.toolStripButtonZK, this.toolStripButtonKH, this.toolStripBtnHSJG, this.toolBtnCheck });
            this.toolbtnBuQi.Location = new Point(0, 0);
            this.toolbtnBuQi.Name = "toolbtnBuQi";
            this.toolbtnBuQi.Size = new Size(0x408, 0x19);
            this.toolbtnBuQi.TabIndex = 0x11d;
            this.toolbtnBuQi.Text = "toolStrip1";
            ((ISupportInitialize) this.dgv_spmx).EndInit();
            this.toolbtnBuQi.ResumeLayout(false);
            this.toolbtnBuQi.PerformLayout();
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(XSDJEdite2));
            this.xmlComponentLoader1 = new XmlComponentLoader();
            base.SuspendLayout();
            this.xmlComponentLoader1.Dock = DockStyle.Fill;
            this.xmlComponentLoader1.Location = new Point(0, 0);
            this.xmlComponentLoader1.Name = "xmlComponentLoader1";
            this.xmlComponentLoader1.Size = new Size(0x418, 0x290);
            this.xmlComponentLoader1.TabIndex = 0;
            this.xmlComponentLoader1.Tag = manager.GetObject("xmlComponentLoader1.Tag");
            this.xmlComponentLoader1.Text = "专普票单据编辑";
            this.xmlComponentLoader1.set_XMLPath(@"..\Config\Components\Aisino.Fwkp.Wbjk.XSDJEdite2\Aisino.Fwkp.Wbjk.XSDJEdite2.xml");
            base.Controls.Add(this.xmlComponentLoader1);
            base.Tag = manager.GetObject("$this.Tag");
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.White;
            base.ClientSize = new Size(0x408, 0x269);
            base.Name = "XSDJEdite2";
            this.Text = "专普票单据编辑";
            base.ResumeLayout(false);
        }
    }
}

