namespace ns3
{
    using Aisino.Fwkp.BusinessObject;
    using System;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential, Size=1)]
    internal struct Struct40
    {
        internal static string string_0;
        internal static int int_0;
        internal static int int_1;
        internal static int int_2;
        internal static int int_3;
        internal static int int_4;
        internal static int int_5;
        internal static int int_6;
        internal static int int_7;
        internal static int int_8;
        internal static int int_9;
        internal static int int_10;
        internal static int int_11;
        internal static int int_12;
        internal static int int_13;
        internal static int int_14;
        internal static int int_15;
        internal static int int_16;
        internal static int int_17;
        internal static int int_18;
        internal static int int_19;
        internal static int int_20;
        internal static int int_21;
        internal static int int_22;
        internal static int int_23;
        internal static int int_24;
        internal static int int_25;
        internal static int int_26;
        internal static int int_27;
        internal static int int_28;
        internal static int int_29;
        internal static int int_30;
        internal static int int_31;
        internal static int int_32;
        internal static int int_33;
        internal static int int_34;
        internal static int int_35;
        internal static int int_36;
        internal static int int_37;
        internal static int int_38;
        internal static int int_39;
        internal static int int_40;
        internal static int int_41;
        internal static int int_42;
        internal static int int_43;
        internal static int int_44;
        internal static int int_45;
        internal static string string_1;
        internal static string string_2;
        internal static string string_3;
        internal static string string_4;
        internal static int int_46;
        internal static int int_47;
        internal static int int_48;
        internal static int int_49;
        internal static int int_50;
        internal static int int_51;
        internal static int int_52;
        internal static int int_53;
        internal static int int_54;
        internal static int int_55;
        internal static string string_5;
        internal static string string_6;
        internal static string string_7;
        internal static string string_8;
        internal static string string_9;
        public static Dictionary<ZYFP_LX, string> dictionary_0;
        internal static string string_10;
        internal static string string_11;
        internal static string string_12;
        internal static string string_13;
        internal static List<string> list_0;
        internal static List<string> list_1;
        internal static List<string> list_2;
        internal static List<string> list_3;
        internal static List<string> list_4;
        internal static List<string> list_5;
        internal static List<string> list_6;
        internal static List<string> list_7;
        internal static string string_14;
        internal static string string_15;
        static Struct40()
        {
            
            string_0 = "0.00";
            int_0 = 20;
            int_1 = 100;
            int_2 = 100;
            int_3 = 100;
            int_4 = 100;
            int_5 = 100;
            int_6 = 8;
            int_7 = 0xf6;
            int_8 = 0x91;
            int_9 = 0x270f;
            int_10 = 0x176f;
            int_11 = 0x12;
            int_12 = 12;
            int_13 = 80;
            int_14 = 80;
            int_15 = 90;
            int_16 = 200;
            int_17 = 30;
            int_18 = 8;
            int_19 = 20;
            int_20 = 40;
            int_21 = 60;
            int_22 = 0x20;
            int_23 = 50;
            int_24 = 0x24;
            int_25 = 0x20;
            int_26 = 50;
            int_27 = 0x17;
            int_28 = 80;
            int_29 = 40;
            int_30 = 80;
            int_31 = 80;
            int_32 = 40;
            int_33 = 8;
            int_34 = 12;
            int_35 = 100;
            int_36 = 100;
            int_37 = 230;
            int_38 = 8;
            int_39 = 8;
            int_40 = 8;
            int_41 = 0x5c;
            int_42 = 12;
            int_43 = 10;
            int_44 = 0x16;
            int_45 = 40;
            string_1 = "0.01";
            string_2 = "0.01";
            string_3 = "0.06";
            string_4 = "1.27";
            int_46 = 15;
            int_47 = 0x15;
            int_48 = 15;
            int_49 = 0x15;
            int_50 = 2;
            int_51 = 0x12;
            int_52 = -1;
            int_53 = 0x12;
            int_54 = 5;
            int_55 = 3;
            string_5 = "(详见销货清单)";
            string_6 = "详见对应正数发票及清单";
            string_7 = "原价合计";
            string_8 = "折扣额合计";
            string_9 = "差额征税";
            Dictionary<ZYFP_LX, string> dictionary = new Dictionary<ZYFP_LX, string>();
            dictionary.Add(ZYFP_LX.SNY, "(石脑油)");
            dictionary.Add(ZYFP_LX.SNY_DDZG, "(石脑油DDZG)");
            dictionary.Add(ZYFP_LX.RLY, "(燃料油)");
            dictionary.Add(ZYFP_LX.RLY_DDZG, "(燃料油DDZG)");
            dictionary_0 = dictionary;
            string_10 = "详见销货清单";
            string_11 = "吨";
            string_12 = "公斤";
            string_13 = "吨";
            list_0 = new List<string>();
            list_1 = new List<string>();
            list_2 = new List<string>();
            list_3 = new List<string>();
            list_4 = new List<string>();
            list_5 = new List<string>();
            list_6 = new List<string>();
            list_7 = new List<string>();
            string_14 = "0.25";
            string_15 = "0.00";
        }
    }
}

