// Assembly Aisino.Framework.Plugin.Core, Version 1.0.1.0

[assembly: System.Runtime.InteropServices.Guid("acd73c08-70db-452b-a1e9-c85cf17e4310")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.1.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
//[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 航天信息股份有限公司 2014-2015")]
[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Reflection.AssemblyTitle("税控发票开票软件（金税盘版）")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Reflection.AssemblyProduct("税控发票开票软件（金税盘版）")]
[assembly: System.Reflection.AssemblyCompany("航天信息股份有限公司")]
[assembly: System.Reflection.AssemblyKeyName("")]

