namespace Aisino.Fwkp.HzfpHy.Form.Common
{
    using System;
    using System.Collections.Generic;

    public class TransportInvInfoTableCommon
    {
        public static List<Dictionary<string, string>> CreateGridHeader()
        {
            List<Dictionary<string, string>> list = new List<Dictionary<string, string>>();
            Dictionary<string, string> item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "红字货物运输业增值税专用发票信息表流水号");
            item.Add("Property", "SQDH");
            item.Add("Width", "330");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "信息表编号");
            item.Add("Property", "XXBBH");
            item.Add("Width", "150");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "信息表状态");
            item.Add("Property", "XXBZT");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "信息表描述");
            item.Add("Property", "XXBMS");
            item.Add("Width", "110");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "发票代码");
            item.Add("Property", "FPDM");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "发票号码");
            item.Add("Property", "FPHM");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "开票机号");
            item.Add("Property", "KPJH");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "实际受票方名称");
            item.Add("Property", "GFMC");
            item.Add("Width", "200");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "实际受票方税号");
            item.Add("Property", "GFSH");
            item.Add("Width", "160");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "承运人名称");
            item.Add("Property", "XFMC");
            item.Add("Width", "200");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "承运人税号");
            item.Add("Property", "XFSH");
            item.Add("Width", "160");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "收货人名称");
            item.Add("Property", "SHRMC");
            item.Add("Width", "200");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "收货人税号");
            item.Add("Property", "SHRSH");
            item.Add("Width", "160");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "发货人名称");
            item.Add("Property", "FHRMC");
            item.Add("Width", "200");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "发货人税号");
            item.Add("Property", "FHRSH");
            item.Add("Width", "160");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "填开日期");
            item.Add("Property", "TKRQ");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "合计金额");
            item.Add("Property", "HJJE");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "税率");
            item.Add("Property", "SL");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "合计税额");
            item.Add("Property", "HJSE");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "运输货物信息");
            item.Add("Property", "YSHWXX");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "机器编号");
            item.Add("Property", "JQBH");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "车种车号");
            item.Add("Property", "CZCH");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "车船吨位");
            item.Add("Property", "CCDW");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "经办人");
            item.Add("Property", "JBR");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "申请选择");
            item.Add("Property", "SQXZ");
            item.Add("Width", "110");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "所属月份");
            item.Add("Property", "SSYF");
            item.Add("Width", "80");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("Name", "colBbbz");
            item.Add("AisinoLBL", "版本标志");
            item.Add("Property", "BBBZ");
            item.Add("Width", "80");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "申请方税号");
            item.Add("Property", "REQNSRSBH");
            item.Add("Width", "160");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleRight");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            item = new Dictionary<string, string>();
            item.Add("AisinoLBL", "分类编码版本号");
            item.Add("Property", "FLBMBBBH");
            item.Add("Width", "100");
            item.Add("Type", "Text");
            item.Add("Align", "MiddleLeft");
            item.Add("HeadAlign", "MiddleCenter");
            list.Add(item);
            return list;
        }
    }
}

