namespace Aisino.Framework.Plugin.Core.Controls
{
    using Aisino.Framework.Plugin.Core.Util;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Drawing.Drawing2D;
    using System.Windows.Forms;

    public class InvoicePaper : UserControl
    {
        private Color color_0;
        public AisinoMultiCombox com_fhr;
        public AisinoMultiCombox com_gfdzdh;
        public AisinoMultiCombox com_gfmc;
        public AisinoMultiCombox com_gfsbh;
        public AisinoMultiCombox com_gfzh;
        public AisinoMultiCombox com_skr;
        public AisinoMultiCombox com_xfdzdh;
        public AisinoMultiCombox com_xfmc;
        public AisinoMultiCombox com_xfsbh;
        public AisinoMultiCombox com_xfzh;
        public PointF DataLoca;
        public CustomStyleDataGrid dgv_spmx;
        private double double_0;
        private double double_1;
        private double double_2;
        private float float_0;
        private float float_1;
        private float float_2;
        private float float_3;
        private float float_4;
        private float float_5;
        private float float_6;
        private Font font_0;
        private IContainer icontainer_0;
        public AisinoLBL lab_Amount;
        private AisinoLBL lab_bz;
        public AisinoLBL lab_fpdm;
        public AisinoLBL lab_fphm;
        private AisinoLBL lab_hj_jshj;
        private AisinoLBL lab_hj_jshj_dx;
        public AisinoLBL lab_hj_xx;
        private AisinoLBL lab_kpr;
        public AisinoLBL lab_kprq;
        private AisinoLBL lab_mmq;
        public AisinoLBL lab_Tax;
        public AisinoLBL lab_title;
        private AisinoLBL label1;
        private AisinoLBL label10;
        private AisinoLBL label11;
        private AisinoLBL label12;
        private AisinoLBL label13;
        private AisinoLBL label17;
        private AisinoLBL label18;
        private AisinoLBL label19;
        private AisinoLBL label2;
        private AisinoLBL label20;
        private AisinoLBL label21;
        private AisinoLBL label23;
        private AisinoLBL label24;
        private AisinoLBL label26;
        private AisinoLBL label27;
        private AisinoLBL label28;
        private AisinoLBL label29;
        private AisinoLBL label3;
        private AisinoLBL label30;
        private AisinoLBL label31;
        private AisinoLBL label32;
        private AisinoLBL label5;
        private AisinoLBL label7;
        private AisinoLBL label8;
        private AisinoLBL label9;
        public AisinoTXT txt_bz;

        public InvoicePaper()
        {
            
            this.float_2 = 120f;
            this.float_3 = 60f;
            this.float_4 = 60f;
            this.float_5 = 110f;
            this.float_6 = 50f;
            this.font_0 = new Font("楷体_GB2312", 8f);
            this.color_0 = Color.Red;
            this.InitializeComponent();
            this.dgv_spmx.GridStyle = CustomStyle.invWare;
            this.BackColor = SystemColors.ActiveCaptionText;
            base.BorderStyle = BorderStyle.FixedSingle;
            this.dgv_spmx.Location = new Point(60, 210);
            this.method_0();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            this.txt_bz = new AisinoTXT();
            this.lab_kprq = new AisinoLBL();
            this.label1 = new AisinoLBL();
            this.lab_title = new AisinoLBL();
            this.label5 = new AisinoLBL();
            this.lab_hj_jshj_dx = new AisinoLBL();
            this.lab_bz = new AisinoLBL();
            this.lab_kpr = new AisinoLBL();
            this.label28 = new AisinoLBL();
            this.label27 = new AisinoLBL();
            this.label26 = new AisinoLBL();
            this.label21 = new AisinoLBL();
            this.label20 = new AisinoLBL();
            this.label19 = new AisinoLBL();
            this.lab_hj_jshj = new AisinoLBL();
            this.label18 = new AisinoLBL();
            this.label13 = new AisinoLBL();
            this.label8 = new AisinoLBL();
            this.lab_mmq = new AisinoLBL();
            this.label9 = new AisinoLBL();
            this.label10 = new AisinoLBL();
            this.label11 = new AisinoLBL();
            this.lab_Tax = new AisinoLBL();
            this.lab_Amount = new AisinoLBL();
            this.label12 = new AisinoLBL();
            this.lab_fphm = new AisinoLBL();
            this.lab_fpdm = new AisinoLBL();
            this.label3 = new AisinoLBL();
            this.label29 = new AisinoLBL();
            this.label24 = new AisinoLBL();
            this.label23 = new AisinoLBL();
            this.label7 = new AisinoLBL();
            this.label17 = new AisinoLBL();
            this.label30 = new AisinoLBL();
            this.label31 = new AisinoLBL();
            this.label32 = new AisinoLBL();
            this.label2 = new AisinoLBL();
            this.lab_hj_xx = new AisinoLBL();
            this.com_skr = new AisinoMultiCombox();
            this.com_fhr = new AisinoMultiCombox();
            this.com_gfzh = new AisinoMultiCombox();
            this.com_gfsbh = new AisinoMultiCombox();
            this.com_xfzh = new AisinoMultiCombox();
            this.com_xfdzdh = new AisinoMultiCombox();
            this.com_xfsbh = new AisinoMultiCombox();
            this.com_xfmc = new AisinoMultiCombox();
            this.com_gfdzdh = new AisinoMultiCombox();
            this.com_gfmc = new AisinoMultiCombox();
            this.dgv_spmx = new CustomStyleDataGrid();
            ((ISupportInitialize) this.dgv_spmx).BeginInit();
            base.SuspendLayout();
            this.txt_bz.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.txt_bz.BorderStyle = BorderStyle.None;
            this.txt_bz.Location = new Point(0x248, 0x1ab);
            this.txt_bz.Multiline = true;
            this.txt_bz.Name = "txt_bz";
            this.txt_bz.Size = new Size(0x146, 0x54);
            this.txt_bz.TabIndex = 9;
            this.lab_kprq.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.lab_kprq.AutoSize = true;
            this.lab_kprq.BackColor = SystemColors.ControlLightLight;
            this.lab_kprq.Font = new Font("宋体", 9f);
            this.lab_kprq.Location = new Point(0x32b, 0x56);
            this.lab_kprq.Name = "lab_kprq";
            this.lab_kprq.Size = new Size(0x29, 12);
            this.lab_kprq.TabIndex = 0x13;
            this.lab_kprq.Text = "年月日";
            this.label1.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.label1.AutoSize = true;
            this.label1.BackColor = SystemColors.ControlLightLight;
            this.label1.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label1.Location = new Point(0x2bb, 0x56);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x35, 12);
            this.label1.TabIndex = 0x12;
            this.label1.Text = "开票日期";
            this.lab_title.Anchor = AnchorStyles.Top;
            this.lab_title.AutoSize = true;
            this.lab_title.BackColor = SystemColors.ControlLightLight;
            this.lab_title.Font = new Font("楷体_GB2312", 14f, FontStyle.Bold);
            this.lab_title.ForeColor = Color.Blue;
            this.lab_title.Location = new Point(400, 0x15);
            this.lab_title.Name = "lab_title";
            this.lab_title.Size = new Size(0x33, 0x13);
            this.lab_title.TabIndex = 14;
            this.lab_title.Text = "标题";
            this.label5.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.label5.AutoSize = true;
            this.label5.BackColor = SystemColors.ControlLightLight;
            this.label5.Font = new Font("楷体_GB2312", 9f);
            this.label5.Location = new Point(0x2b9, 0x20f);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x65, 12);
            this.label5.TabIndex = 13;
            this.label5.Text = "销货单位：（章）";
            this.lab_hj_jshj_dx.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.lab_hj_jshj_dx.AutoSize = true;
            this.lab_hj_jshj_dx.BackColor = SystemColors.ControlLightLight;
            this.lab_hj_jshj_dx.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_hj_jshj_dx.Location = new Point(0x14c, 400);
            this.lab_hj_jshj_dx.Name = "lab_hj_jshj_dx";
            this.lab_hj_jshj_dx.Size = new Size(0x11, 12);
            this.lab_hj_jshj_dx.TabIndex = 0x21;
            this.lab_hj_jshj_dx.Text = "零";
            this.lab_bz.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.lab_bz.AutoSize = true;
            this.lab_bz.BackColor = SystemColors.ControlLightLight;
            this.lab_bz.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_bz.Location = new Point(0x22d, 440);
            this.lab_bz.Name = "lab_bz";
            this.lab_bz.Size = new Size(0x11, 0x48);
            this.lab_bz.TabIndex = 0x26;
            this.lab_bz.Text = "备\r\n\r\n\r\n\r\n\r\n注";
            this.lab_kpr.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.lab_kpr.AutoSize = true;
            this.lab_kpr.BackColor = SystemColors.ControlLightLight;
            this.lab_kpr.Location = new Point(0x255, 0x20f);
            this.lab_kpr.Name = "lab_kpr";
            this.lab_kpr.Size = new Size(0x23, 12);
            this.lab_kpr.TabIndex = 12;
            this.lab_kpr.Text = "admin";
            this.label28.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label28.AutoSize = true;
            this.label28.BackColor = SystemColors.ControlLightLight;
            this.label28.Font = new Font("楷体_GB2312", 9f);
            this.label28.Location = new Point(0x21a, 0x20f);
            this.label28.Name = "label28";
            this.label28.Size = new Size(0x35, 12);
            this.label28.TabIndex = 0x2f;
            this.label28.Text = "开票人：";
            this.label27.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label27.AutoSize = true;
            this.label27.BackColor = SystemColors.ControlLightLight;
            this.label27.Font = new Font("楷体_GB2312", 9f);
            this.label27.Location = new Point(0x128, 0x20f);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x35, 12);
            this.label27.TabIndex = 0x2e;
            this.label27.Text = "复核人：";
            this.label26.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label26.AutoSize = true;
            this.label26.BackColor = SystemColors.ControlLightLight;
            this.label26.Font = new Font("楷体_GB2312", 9f);
            this.label26.Location = new Point(0x47, 0x20f);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x35, 12);
            this.label26.TabIndex = 0x2d;
            this.label26.Text = "收款人：";
            this.label21.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label21.AutoSize = true;
            this.label21.BackColor = SystemColors.ControlLightLight;
            this.label21.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label21.Location = new Point(0x61, 0x1f3);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x59, 12);
            this.label21.TabIndex = 0x2c;
            this.label21.Text = "开户行及账号：";
            this.label20.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label20.AutoSize = true;
            this.label20.BackColor = SystemColors.ControlLightLight;
            this.label20.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label20.Location = new Point(0x61, 0x1db);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x59, 12);
            this.label20.TabIndex = 0x2a;
            this.label20.Text = "地 址、电 话：";
            this.label19.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label19.AutoSize = true;
            this.label19.BackColor = SystemColors.ControlLightLight;
            this.label19.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label19.Location = new Point(0x61, 0x1c3);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x59, 12);
            this.label19.TabIndex = 40;
            this.label19.Text = "纳税人识别号：";
            this.lab_hj_jshj.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.lab_hj_jshj.AutoSize = true;
            this.lab_hj_jshj.BackColor = SystemColors.ControlLightLight;
            this.lab_hj_jshj.Location = new Point(0x451, 490);
            this.lab_hj_jshj.Name = "lab_hj_jshj";
            this.lab_hj_jshj.RightToLeft = RightToLeft.No;
            this.lab_hj_jshj.Size = new Size(11, 12);
            this.lab_hj_jshj.TabIndex = 0x12e;
            this.lab_hj_jshj.Text = "0";
            this.label18.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label18.AutoSize = true;
            this.label18.BackColor = SystemColors.ControlLightLight;
            this.label18.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label18.Location = new Point(0x61, 0x1ab);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x59, 12);
            this.label18.TabIndex = 0x25;
            this.label18.Text = "名        称：";
            this.label13.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label13.AutoSize = true;
            this.label13.BackColor = SystemColors.ControlLightLight;
            this.label13.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label13.Location = new Point(0x53, 0x191);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x65, 12);
            this.label13.TabIndex = 0x20;
            this.label13.Text = "价税合计(大写)：";
            this.label8.AutoSize = true;
            this.label8.BackColor = SystemColors.ControlLightLight;
            this.label8.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label8.Location = new Point(0x61, 0x76);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x59, 12);
            this.label8.TabIndex = 0x15;
            this.label8.Text = "名        称：";
            this.lab_mmq.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.lab_mmq.AutoSize = true;
            this.lab_mmq.BackColor = SystemColors.ControlLightLight;
            this.lab_mmq.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_mmq.Location = new Point(0x22d, 0x88);
            this.lab_mmq.Name = "lab_mmq";
            this.lab_mmq.Size = new Size(0x11, 60);
            this.lab_mmq.TabIndex = 0x16;
            this.lab_mmq.Text = "密\r\n\r\n码\r\n\r\n区";
            this.label9.AutoSize = true;
            this.label9.BackColor = SystemColors.ControlLightLight;
            this.label9.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label9.Location = new Point(0x61, 0x8e);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x59, 12);
            this.label9.TabIndex = 0x18;
            this.label9.Text = "纳税人识别号：";
            this.label10.AutoSize = true;
            this.label10.BackColor = SystemColors.ControlLightLight;
            this.label10.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label10.Location = new Point(0x61, 0xa6);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x59, 12);
            this.label10.TabIndex = 0x1a;
            this.label10.Text = "地 址、电 话：";
            this.label11.AutoSize = true;
            this.label11.BackColor = SystemColors.ControlLightLight;
            this.label11.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label11.Location = new Point(0x61, 190);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x59, 12);
            this.label11.TabIndex = 0x1c;
            this.label11.Text = "开户行及账号：";
            this.lab_Tax.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.lab_Tax.AutoSize = true;
            this.lab_Tax.BackColor = SystemColors.ControlLightLight;
            this.lab_Tax.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_Tax.Location = new Point(0x346, 0x17a);
            this.lab_Tax.Name = "lab_Tax";
            this.lab_Tax.Size = new Size(0x29, 12);
            this.lab_Tax.TabIndex = 0x1f;
            this.lab_Tax.Text = "税额：";
            this.lab_Amount.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.lab_Amount.AutoSize = true;
            this.lab_Amount.BackColor = SystemColors.ControlLightLight;
            this.lab_Amount.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_Amount.Location = new Point(0x290, 0x17a);
            this.lab_Amount.Name = "lab_Amount";
            this.lab_Amount.Size = new Size(0x29, 12);
            this.lab_Amount.TabIndex = 30;
            this.lab_Amount.Text = "金额：";
            this.label12.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label12.AutoSize = true;
            this.label12.BackColor = SystemColors.ControlLightLight;
            this.label12.Font = new Font("楷体_GB2312", 9f);
            this.label12.Location = new Point(0x6b, 0x17a);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x41, 12);
            this.label12.TabIndex = 0x1d;
            this.label12.Text = "合      计";
            this.lab_fphm.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.lab_fphm.AutoSize = true;
            this.lab_fphm.BackColor = SystemColors.ButtonHighlight;
            this.lab_fphm.Font = new Font("楷体_GB2312", 13f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.lab_fphm.ForeColor = Color.Maroon;
            this.lab_fphm.Location = new Point(0x2b9, 0x31);
            this.lab_fphm.Name = "lab_fphm";
            this.lab_fphm.Size = new Size(0x58, 0x12);
            this.lab_fphm.TabIndex = 0x11;
            this.lab_fphm.Text = "00000000";
            this.lab_fpdm.AutoSize = true;
            this.lab_fpdm.BackColor = SystemColors.ButtonHighlight;
            this.lab_fpdm.Font = new Font("楷体_GB2312", 13f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.lab_fpdm.ForeColor = Color.Maroon;
            this.lab_fpdm.Location = new Point(0x7c, 0x31);
            this.lab_fpdm.Name = "lab_fpdm";
            this.lab_fpdm.Size = new Size(0x6c, 0x12);
            this.lab_fpdm.TabIndex = 15;
            this.lab_fpdm.Text = "0000000000";
            this.label3.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.label3.AutoSize = true;
            this.label3.BackColor = SystemColors.ButtonHighlight;
            this.label3.Font = new Font("Script MT Bold", 13f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label3.Location = new Point(0x27f, 0x2b);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x34, 0x16);
            this.label3.TabIndex = 0x10;
            this.label3.Text = "No：";
            this.label29.AutoSize = true;
            this.label29.BackColor = SystemColors.ButtonHighlight;
            this.label29.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label29.Location = new Point(0x44, 190);
            this.label29.Name = "label29";
            this.label29.Size = new Size(0x11, 12);
            this.label29.TabIndex = 0x1b;
            this.label29.Text = "位";
            this.label24.AutoSize = true;
            this.label24.BackColor = SystemColors.ButtonHighlight;
            this.label24.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label24.Location = new Point(0x44, 0xa6);
            this.label24.Name = "label24";
            this.label24.Size = new Size(0x11, 12);
            this.label24.TabIndex = 0x19;
            this.label24.Text = "单";
            this.label23.AutoSize = true;
            this.label23.BackColor = SystemColors.ButtonHighlight;
            this.label23.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label23.Location = new Point(0x44, 0x8e);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x11, 12);
            this.label23.TabIndex = 0x17;
            this.label23.Text = "货";
            this.label7.AutoSize = true;
            this.label7.BackColor = SystemColors.ButtonHighlight;
            this.label7.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label7.Location = new Point(0x44, 0x76);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x11, 12);
            this.label7.TabIndex = 20;
            this.label7.Text = "购";
            this.label17.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label17.AutoSize = true;
            this.label17.BackColor = SystemColors.ButtonHighlight;
            this.label17.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label17.Location = new Point(70, 0x1ab);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x11, 12);
            this.label17.TabIndex = 0x24;
            this.label17.Text = "销";
            this.label30.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label30.AutoSize = true;
            this.label30.BackColor = SystemColors.ButtonHighlight;
            this.label30.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label30.Location = new Point(70, 0x1f3);
            this.label30.Name = "label30";
            this.label30.Size = new Size(0x11, 12);
            this.label30.TabIndex = 0x2b;
            this.label30.Text = "位";
            this.label31.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label31.AutoSize = true;
            this.label31.BackColor = SystemColors.ButtonHighlight;
            this.label31.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label31.Location = new Point(70, 0x1db);
            this.label31.Name = "label31";
            this.label31.Size = new Size(0x11, 12);
            this.label31.TabIndex = 0x29;
            this.label31.Text = "单";
            this.label32.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label32.AutoSize = true;
            this.label32.BackColor = SystemColors.ButtonHighlight;
            this.label32.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label32.Location = new Point(70, 0x1c3);
            this.label32.Name = "label32";
            this.label32.Size = new Size(0x11, 12);
            this.label32.TabIndex = 0x27;
            this.label32.Text = "货";
            this.label2.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.label2.AutoSize = true;
            this.label2.BackColor = SystemColors.ControlLightLight;
            this.label2.Font = new Font("楷体_GB2312", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label2.Location = new Point(0x290, 400);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x35, 12);
            this.label2.TabIndex = 0x22;
            this.label2.Text = "(小写)：";
            this.lab_hj_xx.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.lab_hj_xx.AutoSize = true;
            this.lab_hj_xx.BackColor = SystemColors.ControlLightLight;
            this.lab_hj_xx.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_hj_xx.Location = new Point(0x2e3, 0x192);
            this.lab_hj_xx.Name = "lab_hj_xx";
            this.lab_hj_xx.Size = new Size(11, 12);
            this.lab_hj_xx.TabIndex = 0x23;
            this.lab_hj_xx.Text = "0";
            this.com_skr.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_skr.AutoComplate = AutoComplateStyle.None;
            this.com_skr.AutoIndex = 1;
            this.com_skr.BorderColor = SystemColors.Control;
            this.com_skr.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_skr.ButtonAutoHide = true;
            this.com_skr.buttonStyle = ButtonStyle.Select;
            this.com_skr.DataSource = null;
            this.com_skr.DrawHead = true;
            this.com_skr.Edit = EditStyle.TextBox;
            this.com_skr.IsSelectAll = false;
            this.com_skr.Location = new Point(0x80, 0x20b);
            this.com_skr.MaxIndex = 8;
            this.com_skr.Name = "com_skr";
            this.com_skr.ReadOnly = false;
            this.com_skr.SelectedIndex = -1;
            this.com_skr.ShowText = "";
            this.com_skr.Size = new Size(0x45, 0x15);
            this.com_skr.TabIndex = 10;
            this.com_skr.UnderLineColor = Color.Transparent;
            this.com_skr.UnderLineStyle = AisinoComboxBorderStyle.None;
            this.com_fhr.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_fhr.AutoComplate = AutoComplateStyle.None;
            this.com_fhr.AutoIndex = 1;
            this.com_fhr.BorderColor = SystemColors.Control;
            this.com_fhr.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_fhr.ButtonAutoHide = true;
            this.com_fhr.buttonStyle = ButtonStyle.Select;
            this.com_fhr.DataSource = null;
            this.com_fhr.DrawHead = true;
            this.com_fhr.Edit = EditStyle.TextBox;
            this.com_fhr.IsSelectAll = false;
            this.com_fhr.Location = new Point(0x163, 0x20b);
            this.com_fhr.MaxIndex = 8;
            this.com_fhr.Name = "com_fhr";
            this.com_fhr.ReadOnly = false;
            this.com_fhr.SelectedIndex = -1;
            this.com_fhr.ShowText = "";
            this.com_fhr.Size = new Size(0x45, 0x15);
            this.com_fhr.TabIndex = 11;
            this.com_fhr.UnderLineColor = Color.Transparent;
            this.com_fhr.UnderLineStyle = AisinoComboxBorderStyle.None;
            this.com_gfzh.AutoComplate = AutoComplateStyle.None;
            this.com_gfzh.AutoIndex = 1;
            this.com_gfzh.BorderColor = SystemColors.Control;
            this.com_gfzh.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_gfzh.ButtonAutoHide = true;
            this.com_gfzh.buttonStyle = ButtonStyle.Select;
            this.com_gfzh.DataSource = null;
            this.com_gfzh.DrawHead = true;
            this.com_gfzh.Edit = EditStyle.TextBox;
            this.com_gfzh.IsSelectAll = false;
            this.com_gfzh.Location = new Point(0xc7, 0xbb);
            this.com_gfzh.MaxIndex = 8;
            this.com_gfzh.Name = "com_gfzh";
            this.com_gfzh.ReadOnly = false;
            this.com_gfzh.SelectedIndex = -1;
            this.com_gfzh.ShowText = "";
            this.com_gfzh.Size = new Size(0x160, 0x15);
            this.com_gfzh.TabIndex = 3;
            this.com_gfzh.UnderLineColor = Color.Transparent;
            this.com_gfzh.UnderLineStyle = AisinoComboxBorderStyle.System;
            this.com_gfsbh.AutoComplate = AutoComplateStyle.None;
            this.com_gfsbh.AutoIndex = 1;
            this.com_gfsbh.BorderColor = SystemColors.Control;
            this.com_gfsbh.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_gfsbh.ButtonAutoHide = true;
            this.com_gfsbh.buttonStyle = ButtonStyle.Select;
            this.com_gfsbh.DataSource = null;
            this.com_gfsbh.DrawHead = true;
            this.com_gfsbh.Edit = EditStyle.TextBox;
            this.com_gfsbh.IsSelectAll = false;
            this.com_gfsbh.Location = new Point(0xc7, 0x8d);
            this.com_gfsbh.MaxIndex = 8;
            this.com_gfsbh.Name = "com_gfsbh";
            this.com_gfsbh.ReadOnly = false;
            this.com_gfsbh.SelectedIndex = -1;
            this.com_gfsbh.ShowText = "";
            this.com_gfsbh.Size = new Size(0x160, 0x15);
            this.com_gfsbh.TabIndex = 1;
            this.com_gfsbh.UnderLineColor = Color.Transparent;
            this.com_gfsbh.UnderLineStyle = AisinoComboxBorderStyle.System;
            this.com_xfzh.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_xfzh.AutoComplate = AutoComplateStyle.None;
            this.com_xfzh.AutoIndex = 1;
            this.com_xfzh.BorderColor = SystemColors.Control;
            this.com_xfzh.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_xfzh.ButtonAutoHide = true;
            this.com_xfzh.buttonStyle = ButtonStyle.Select;
            this.com_xfzh.DataSource = null;
            this.com_xfzh.DrawHead = true;
            this.com_xfzh.Edit = EditStyle.TextBox;
            this.com_xfzh.IsSelectAll = false;
            this.com_xfzh.Location = new Point(190, 0x1f0);
            this.com_xfzh.MaxIndex = 8;
            this.com_xfzh.Name = "com_xfzh";
            this.com_xfzh.ReadOnly = false;
            this.com_xfzh.SelectedIndex = -1;
            this.com_xfzh.ShowText = "";
            this.com_xfzh.Size = new Size(0x169, 0x15);
            this.com_xfzh.TabIndex = 8;
            this.com_xfzh.UnderLineColor = Color.Transparent;
            this.com_xfzh.UnderLineStyle = AisinoComboxBorderStyle.System;
            this.com_xfdzdh.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_xfdzdh.AutoComplate = AutoComplateStyle.None;
            this.com_xfdzdh.AutoIndex = 1;
            this.com_xfdzdh.BorderColor = SystemColors.Control;
            this.com_xfdzdh.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_xfdzdh.ButtonAutoHide = true;
            this.com_xfdzdh.buttonStyle = ButtonStyle.Select;
            this.com_xfdzdh.DataSource = null;
            this.com_xfdzdh.DrawHead = true;
            this.com_xfdzdh.Edit = EditStyle.TextBox;
            this.com_xfdzdh.IsSelectAll = false;
            this.com_xfdzdh.Location = new Point(190, 0x1d9);
            this.com_xfdzdh.MaxIndex = 8;
            this.com_xfdzdh.Name = "com_xfdzdh";
            this.com_xfdzdh.ReadOnly = false;
            this.com_xfdzdh.SelectedIndex = -1;
            this.com_xfdzdh.ShowText = "";
            this.com_xfdzdh.Size = new Size(0x169, 0x15);
            this.com_xfdzdh.TabIndex = 7;
            this.com_xfdzdh.UnderLineColor = Color.Transparent;
            this.com_xfdzdh.UnderLineStyle = AisinoComboxBorderStyle.System;
            this.com_xfsbh.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_xfsbh.AutoComplate = AutoComplateStyle.None;
            this.com_xfsbh.AutoIndex = 1;
            this.com_xfsbh.BorderColor = SystemColors.Control;
            this.com_xfsbh.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_xfsbh.ButtonAutoHide = true;
            this.com_xfsbh.buttonStyle = ButtonStyle.Select;
            this.com_xfsbh.DataSource = null;
            this.com_xfsbh.DrawHead = true;
            this.com_xfsbh.Edit = EditStyle.TextBox;
            this.com_xfsbh.IsSelectAll = false;
            this.com_xfsbh.Location = new Point(190, 450);
            this.com_xfsbh.MaxIndex = 8;
            this.com_xfsbh.Name = "com_xfsbh";
            this.com_xfsbh.ReadOnly = false;
            this.com_xfsbh.SelectedIndex = -1;
            this.com_xfsbh.ShowText = "";
            this.com_xfsbh.Size = new Size(0x169, 0x15);
            this.com_xfsbh.TabIndex = 6;
            this.com_xfsbh.UnderLineColor = Color.Transparent;
            this.com_xfsbh.UnderLineStyle = AisinoComboxBorderStyle.System;
            this.com_xfmc.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.com_xfmc.AutoComplate = AutoComplateStyle.None;
            this.com_xfmc.AutoIndex = 1;
            this.com_xfmc.BorderColor = SystemColors.Control;
            this.com_xfmc.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_xfmc.ButtonAutoHide = true;
            this.com_xfmc.buttonStyle = ButtonStyle.Select;
            this.com_xfmc.DataSource = null;
            this.com_xfmc.DrawHead = true;
            this.com_xfmc.Edit = EditStyle.TextBox;
            this.com_xfmc.IsSelectAll = false;
            this.com_xfmc.Location = new Point(190, 0x1ab);
            this.com_xfmc.MaxIndex = 8;
            this.com_xfmc.Name = "com_xfmc";
            this.com_xfmc.ReadOnly = false;
            this.com_xfmc.SelectedIndex = -1;
            this.com_xfmc.ShowText = "";
            this.com_xfmc.Size = new Size(0x169, 0x15);
            this.com_xfmc.TabIndex = 5;
            this.com_xfmc.UnderLineColor = Color.Transparent;
            this.com_xfmc.UnderLineStyle = AisinoComboxBorderStyle.System;
            this.com_gfdzdh.AutoComplate = AutoComplateStyle.None;
            this.com_gfdzdh.AutoIndex = 1;
            this.com_gfdzdh.BorderColor = SystemColors.Control;
            this.com_gfdzdh.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_gfdzdh.ButtonAutoHide = true;
            this.com_gfdzdh.buttonStyle = ButtonStyle.Select;
            this.com_gfdzdh.DataSource = null;
            this.com_gfdzdh.DrawHead = true;
            this.com_gfdzdh.Edit = EditStyle.TextBox;
            this.com_gfdzdh.IsSelectAll = false;
            this.com_gfdzdh.Location = new Point(0xc7, 0xa4);
            this.com_gfdzdh.MaxIndex = 8;
            this.com_gfdzdh.Name = "com_gfdzdh";
            this.com_gfdzdh.ReadOnly = false;
            this.com_gfdzdh.SelectedIndex = -1;
            this.com_gfdzdh.ShowText = "";
            this.com_gfdzdh.Size = new Size(0x160, 0x15);
            this.com_gfdzdh.TabIndex = 2;
            this.com_gfdzdh.UnderLineColor = Color.Transparent;
            this.com_gfdzdh.UnderLineStyle = AisinoComboxBorderStyle.System;
            this.com_gfmc.AutoComplate = AutoComplateStyle.None;
            this.com_gfmc.AutoIndex = 1;
            this.com_gfmc.BorderColor = SystemColors.Control;
            this.com_gfmc.BorderStyle = AisinoComboxBorderStyle.System;
            this.com_gfmc.ButtonAutoHide = true;
            this.com_gfmc.buttonStyle = ButtonStyle.Select;
            this.com_gfmc.DataSource = null;
            this.com_gfmc.DrawHead = true;
            this.com_gfmc.Edit = EditStyle.TextBox;
            this.com_gfmc.ForeColor = Color.Maroon;
            this.com_gfmc.IsSelectAll = false;
            this.com_gfmc.Location = new Point(0xc7, 0x76);
            this.com_gfmc.MaxIndex = 8;
            this.com_gfmc.Name = "com_gfmc";
            this.com_gfmc.ReadOnly = false;
            this.com_gfmc.SelectedIndex = -1;
            this.com_gfmc.ShowText = "";
            this.com_gfmc.Size = new Size(0x160, 0x15);
            this.com_gfmc.TabIndex = 0;
            this.com_gfmc.UnderLineColor = Color.Transparent;
            this.com_gfmc.UnderLineStyle = AisinoComboxBorderStyle.System;
            this.dgv_spmx.AborCellPainting = false;
            this.dgv_spmx.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.dgv_spmx.BackgroundColor = SystemColors.ButtonHighlight;
            this.dgv_spmx.BorderStyle = BorderStyle.None;
            style.Alignment = DataGridViewContentAlignment.MiddleCenter;
            style.BackColor = SystemColors.Control;
            style.Font = new Font("楷体_GB2312", 9f);
            style.ForeColor = SystemColors.WindowText;
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.False;
            this.dgv_spmx.ColumnHeadersDefaultCellStyle = style;
            this.dgv_spmx.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgv_spmx.GridColor = Color.Gray;
            this.dgv_spmx.GridStyle = CustomStyle.custom;
            this.dgv_spmx.Location = new Point(0x3e, 0xd6);
            this.dgv_spmx.Name = "dgv_spmx";
            this.dgv_spmx.RowHeadersVisible = false;
            this.dgv_spmx.RowTemplate.Height = 0x17;
            this.dgv_spmx.ScrollBars = ScrollBars.Vertical;
            this.dgv_spmx.SelectionMode = DataGridViewSelectionMode.CellSelect;
            this.dgv_spmx.Size = new Size(0x365, 0xba);
            this.dgv_spmx.TabIndex = 4;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.Controls.Add(this.lab_hj_xx);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.com_skr);
            base.Controls.Add(this.com_fhr);
            base.Controls.Add(this.com_gfzh);
            base.Controls.Add(this.com_gfsbh);
            base.Controls.Add(this.com_xfzh);
            base.Controls.Add(this.com_xfdzdh);
            base.Controls.Add(this.com_xfsbh);
            base.Controls.Add(this.com_xfmc);
            base.Controls.Add(this.com_gfdzdh);
            base.Controls.Add(this.com_gfmc);
            base.Controls.Add(this.label17);
            base.Controls.Add(this.label30);
            base.Controls.Add(this.label31);
            base.Controls.Add(this.label32);
            base.Controls.Add(this.label29);
            base.Controls.Add(this.label24);
            base.Controls.Add(this.label23);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.lab_fphm);
            base.Controls.Add(this.lab_fpdm);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.lab_Tax);
            base.Controls.Add(this.lab_Amount);
            base.Controls.Add(this.label12);
            base.Controls.Add(this.dgv_spmx);
            base.Controls.Add(this.txt_bz);
            base.Controls.Add(this.lab_kprq);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.lab_title);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.lab_hj_jshj_dx);
            base.Controls.Add(this.lab_bz);
            base.Controls.Add(this.lab_kpr);
            base.Controls.Add(this.label28);
            base.Controls.Add(this.label27);
            base.Controls.Add(this.label26);
            base.Controls.Add(this.label21);
            base.Controls.Add(this.label20);
            base.Controls.Add(this.label19);
            base.Controls.Add(this.lab_hj_jshj);
            base.Controls.Add(this.label18);
            base.Controls.Add(this.label13);
            base.Controls.Add(this.label8);
            base.Controls.Add(this.lab_mmq);
            base.Controls.Add(this.label9);
            base.Controls.Add(this.label10);
            base.Controls.Add(this.label11);
            base.Name = "InvoicePaper";
            base.Size = new Size(0x3da, 0x238);
            ((ISupportInitialize) this.dgv_spmx).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private void method_0()
        {
            this.dgv_spmx.Columns.Add("SPMC", "货物或应税劳务名称");
            this.dgv_spmx.Columns.Add("GGXH", "规格型号");
            this.dgv_spmx.Columns.Add("JLDW", "单位");
            this.dgv_spmx.Columns.Add("SL", "数量");
            this.dgv_spmx.Columns.Add("DJ", "单价");
            this.dgv_spmx.Columns.Add("JE", "金额");
            this.dgv_spmx.Columns.Add("SLV", "税率");
            this.dgv_spmx.Columns.Add("SE", "税额");
            this.dgv_spmx.Columns.Add("DJHXZ", "单据行性质");
            this.dgv_spmx.Columns["SPMC"].Width = 0xf5;
            this.dgv_spmx.Columns["GGXH"].Width = 100;
            this.dgv_spmx.Columns["JLDW"].Width = 60;
            this.dgv_spmx.Columns["SL"].Width = 90;
            this.dgv_spmx.Columns["DJ"].Width = 0x55;
            this.dgv_spmx.Columns["JE"].Width = 110;
            this.dgv_spmx.Columns["SLV"].Width = 50;
            this.dgv_spmx.Columns["SE"].Width = 110;
            this.dgv_spmx.Columns["DJHXZ"].Visible = false;
            this.dgv_spmx.Columns["JE"].DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.dgv_spmx.Columns["SE"].DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.dgv_spmx.Columns["SL"].DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.dgv_spmx.Columns["DJ"].DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.dgv_spmx.Columns["SLV"].DefaultCellStyle.Format = "0%";
            this.dgv_spmx.Columns["SLV"].DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
        }

        private void method_1(Graphics graphics_0)
        {
            PointF tf = new PointF(this.float_3, this.float_5);
            PointF tf2 = new PointF(base.Width - this.float_4, this.float_5);
            PointF tf3 = new PointF(this.float_3, base.Height - this.float_6);
            PointF tf4 = new PointF(base.Width - this.float_4, base.Height - this.float_6);
            float num = 100f;
            PointF tf5 = new PointF(tf.X, tf.Y + num);
            PointF tf6 = new PointF(tf2.X, tf2.Y + num);
            PointF tf7 = this.method_2(tf3, 0f, -100f);
            PointF tf8 = this.method_2(tf4, 0f, -100f);
            PointF tf9 = this.method_2(tf7, 0f, -25f);
            PointF tf10 = this.method_2(tf8, 0f, -25f);
            float num2 = 30f;
            PointF tf11 = this.method_2(tf, num2, 0f);
            PointF tf12 = this.method_2(tf5, num2, 0f);
            PointF tf13 = this.method_2(tf7, num2, 0f);
            PointF tf14 = this.method_2(tf3, num2, 0f);
            float num3 = 47f * this.float_0;
            PointF tf15 = this.method_2(tf, num2 + num3, 0f);
            this.lab_mmq.Location = this.method_3(tf15);
            PointF tf16 = this.method_2(tf5, num2 + num3, 0f);
            PointF tf17 = this.method_2(tf7, num2 + num3, 0f);
            this.lab_bz.Location = this.method_3(tf17);
            PointF tf18 = this.method_2(tf3, num2 + num3, 0f);
            this.com_gfmc.Width = Convert.ToInt32((float) (num3 - 120f));
            this.com_gfsbh.Width = Convert.ToInt32((float) (num3 - 120f));
            this.com_gfzh.Width = Convert.ToInt32((float) (num3 - 120f));
            this.com_gfdzdh.Width = Convert.ToInt32((float) (num3 - 120f));
            this.com_xfdzdh.Width = Convert.ToInt32((float) (num3 - 120f));
            this.com_xfmc.Width = Convert.ToInt32((float) (num3 - 120f));
            this.com_xfsbh.Width = Convert.ToInt32((float) (num3 - 120f));
            this.com_xfzh.Width = Convert.ToInt32((float) (num3 - 120f));
            float num4 = 25f;
            PointF tf19 = this.method_2(tf, (num2 + num3) + num4, 0f);
            PointF tf20 = this.method_2(tf5, (num2 + num3) + num4, 0f);
            PointF tf21 = this.method_2(tf7, (num2 + num3) + num4, 0f);
            this.txt_bz.Location = this.method_3(tf21);
            this.txt_bz.Width = (base.Width - Convert.ToInt32((float) ((((this.float_3 + num2) + num3) + num4) + this.float_4))) - 10;
            PointF tf22 = this.method_2(tf3, (num2 + num3) + num4, 0f);
            PointF tf23 = this.method_2(tf9, (float) (base.Width / 4), 0f);
            PointF tf24 = this.method_2(tf7, (float) (base.Width / 4), 0f);
            using (Pen pen = new Pen(Color.Black))
            {
                graphics_0.DrawLine(pen, tf, tf2);
                graphics_0.DrawLine(pen, tf2, tf4);
                graphics_0.DrawLine(pen, tf, tf3);
                graphics_0.DrawLine(pen, tf3, tf4);
                graphics_0.DrawLine(pen, tf5, tf6);
                graphics_0.DrawLine(pen, tf9, tf10);
                graphics_0.DrawLine(pen, tf7, tf8);
                graphics_0.DrawLine(pen, tf11, tf12);
                graphics_0.DrawLine(pen, tf13, tf14);
                graphics_0.DrawLine(pen, tf15, tf16);
                graphics_0.DrawLine(pen, tf17, tf18);
                graphics_0.DrawLine(pen, tf19, tf20);
                graphics_0.DrawLine(pen, tf21, tf22);
                graphics_0.DrawLine(pen, tf23, tf24);
                graphics_0.DrawLine(pen, (float) (35f * this.float_0), (float) ((this.float_2 / 2f) + 10f), (float) (65f * this.float_0), (float) ((this.float_2 / 2f) + 10f));
                graphics_0.DrawLine(pen, (float) (35f * this.float_0), (float) ((this.float_2 / 2f) + 3f), (float) (65f * this.float_0), (float) ((this.float_2 / 2f) + 3f));
            }
            float num5 = 50f;
            float y = 10f;
            float width = 15f;
            while (y < base.Height)
            {
                graphics_0.FillEllipse(SystemBrushes.ControlDark, 10f, y, width, width);
                graphics_0.FillEllipse(SystemBrushes.ControlDark, (float) (base.Width - 30), y, width, width);
                y += num5;
            }
        }

        private PointF method_2(PointF pointF_0, float float_7, float float_8)
        {
            return new PointF(pointF_0.X + float_7, pointF_0.Y + float_8);
        }

        private Point method_3(PointF pointF_0)
        {
            return new Point(Convert.ToInt32(pointF_0.X) + 2, Convert.ToInt32(pointF_0.Y) + 5);
        }

        private void method_4(Graphics graphics_0)
        {
            string text = this.Text;
            Font font = this.Font;
            Brush controlLightLight = SystemBrushes.ControlLightLight;
            StringFormat format = new StringFormat {
                Alignment = StringAlignment.Center
            };
            Rectangle layoutRectangle = new Rectangle(4, 4, base.Width - 8, base.Height - 8);
            graphics_0.DrawString(text, font, controlLightLight, layoutRectangle, format);
        }

        private void method_5(Graphics graphics_0, string string_0, float float_7, PointF pointF_0)
        {
            StringFormat format = new StringFormat {
                Alignment = StringAlignment.Center,
                LineAlignment = StringAlignment.Center
            };
            GraphicsPath path = new GraphicsPath(FillMode.Winding);
            int x = (int) pointF_0.X;
            int y = (int) pointF_0.Y;
            path.AddString(string_0, this.font_0.FontFamily, (int) this.font_0.Style, this.font_0.Size, new Point(x, y), format);
            Matrix matrix = new Matrix();
            matrix.RotateAt(float_7, new PointF((float) x, (float) y));
            graphics_0.Transform = matrix;
            graphics_0.DrawPath(new Pen(this.color_0), path);
            graphics_0.FillPath(new SolidBrush(this.color_0), path);
        }

        protected override void OnPaint(PaintEventArgs e)
        {
            base.OnPaint(e);
            this.float_0 = ((float) base.Width) / 100f;
            this.float_1 = ((float) base.Height) / 100f;
            Graphics graphics = e.Graphics;
            this.method_1(graphics);
        }

        public void SetJeSe(double double_3, double double_4)
        {
            this.double_0 = double_3;
            this.double_1 = double_4;
            this.double_2 = double_3 + double_4;
            this.lab_Amount.Text = double_3.ToString("C");
            this.lab_Tax.Text = double_4.ToString("C");
            this.lab_hj_xx.Text = (double_3 + double_4).ToString("C");
            this.lab_hj_jshj_dx.Text = "㊣ " + ToolUtil.RMBToDaXie(Convert.ToDecimal((double) (double_3 + double_4)));
        }

        public double HJJE
        {
            get
            {
                return this.double_0;
            }
        }

        public double HJJeSe
        {
            get
            {
                return this.double_2;
            }
        }

        public double HJSE
        {
            get
            {
                return this.double_1;
            }
        }
    }
}

