namespace Aisino.Framework.Plugin.Core.Controls
{
    using Aisino.Framework.Plugin.Core.Util;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class InvoiceLittle : UserControl
    {
        public decimal _AmountTotal;
        public string _BZ;
        public string _FHR;
        public string _FPDM;
        public string _FPHM;
        public string _FPLX;
        public string _GFDZDH;
        public string _GFMC;
        public string _GFSH;
        public string _GFYHZH;
        public string _KPR;
        public string _KPRQ;
        public string _SKR;
        public decimal _TaxTotal;
        public string _XFDZDH;
        public string _XFMC;
        public string _XFSH;
        public string _XFYHZH;
        private AisinoLBL AmountTotal;
        private AisinoLBL BZ;
        private AisinoLBL DJ1;
        private AisinoLBL DJ2;
        private AisinoLBL DJ3;
        private AisinoLBL DJ4;
        private AisinoLBL DJ5;
        private AisinoLBL DJ6;
        private AisinoLBL DJ7;
        private AisinoLBL DW1;
        private AisinoLBL DW2;
        private AisinoLBL DW3;
        private AisinoLBL DW4;
        private AisinoLBL DW5;
        private AisinoLBL DW6;
        private AisinoLBL DW7;
        private AisinoLBL FHR;
        private AisinoLBL GFDZDH;
        private AisinoLBL GFMC;
        private AisinoLBL GFSH;
        private AisinoLBL GFYHZH;
        private AisinoLBL GGXH1;
        private AisinoLBL GGXH2;
        private AisinoLBL GGXH3;
        private AisinoLBL GGXH4;
        private AisinoLBL GGXH5;
        private AisinoLBL GGXH6;
        private AisinoLBL GGXH7;
        private IContainer icontainer_0;
        private InvoicePanelLt invoicePanelLt1;
        private AisinoLBL JE1;
        private AisinoLBL JE2;
        private AisinoLBL JE3;
        private AisinoLBL JE4;
        private AisinoLBL JE5;
        private AisinoLBL JE6;
        private AisinoLBL JE7;
        private AisinoLBL KPR;
        private AisinoLBL KPRQ;
        public AisinoLBL lab_fpdm;
        public AisinoLBL lab_fphm;
        private AisinoLBL lab_hj_dx;
        private AisinoLBL lab_hj_jshj;
        public AisinoLBL lab_hj_xx;
        private AisinoLBL lab_title;
        private AisinoLBL label1;
        private AisinoLBL label10;
        private AisinoLBL label11;
        private AisinoLBL label12;
        private AisinoLBL label13;
        private AisinoLBL label16;
        private AisinoLBL label17;
        private AisinoLBL label18;
        private AisinoLBL label19;
        private AisinoLBL label2;
        private AisinoLBL label20;
        private AisinoLBL label21;
        private AisinoLBL label22;
        private AisinoLBL label23;
        private AisinoLBL label24;
        private AisinoLBL label25;
        private AisinoLBL label26;
        private AisinoLBL label27;
        private AisinoLBL label28;
        private AisinoLBL label29;
        private AisinoLBL label3;
        private AisinoLBL label30;
        private AisinoLBL label31;
        private AisinoLBL label32;
        private AisinoLBL label4;
        private AisinoLBL label5;
        private AisinoLBL label6;
        private AisinoLBL label7;
        private AisinoLBL label8;
        private AisinoLBL label9;
        private List<string[]> list_0;
        private AisinoLBL SE1;
        private AisinoLBL SE2;
        private AisinoLBL SE3;
        private AisinoLBL SE4;
        private AisinoLBL SE5;
        private AisinoLBL SE6;
        private AisinoLBL SE7;
        private AisinoLBL SKR;
        private AisinoLBL SL1;
        private AisinoLBL SL2;
        private AisinoLBL SL3;
        private AisinoLBL SL4;
        private AisinoLBL SL5;
        private AisinoLBL SL6;
        private AisinoLBL SL7;
        private AisinoLBL SLV1;
        private AisinoLBL SLV2;
        private AisinoLBL SLV3;
        private AisinoLBL SLV4;
        private AisinoLBL SLV5;
        private AisinoLBL SLV6;
        private AisinoLBL SLV7;
        private AisinoLBL SPMC1;
        private AisinoLBL SPMC2;
        private AisinoLBL SPMC3;
        private AisinoLBL SPMC4;
        private AisinoLBL SPMC5;
        private AisinoLBL SPMC6;
        private AisinoLBL SPMC7;
        private AisinoLBL TaxTotal;
        private AisinoLBL XFDZDH;
        private AisinoLBL XFMC;
        private AisinoLBL XFSH;
        private AisinoLBL XFYHZH;

        public InvoiceLittle()
        {
            
            this.list_0 = new List<string[]>();
            this.InitializeComponent();
            this.method_0();
            this.method_1();
        }

        public void AddWare(string string_0, string string_1, string string_2, double double_0, double double_1, double double_2, double double_3, double double_4)
        {
            if (this.list_0.Count > 7)
            {
                throw new Exception("商品已购7行");
            }
            string str = (double_0 == 0.0) ? " " : double_0.ToString();
            string str2 = (double_1 == 0.0) ? " " : double_1.ToString();
            string str3 = double_2.ToString("0.00");
            string str4 = double_4.ToString("0.00");
            string str5 = double_3.ToString("0%");
            string[] item = new string[] { string_0, string_1, string_2, str, str2, str3, str4, str5 };
            this.list_0.Add(item);
        }

        public void AddWare(string string_0, string string_1, string string_2, string string_3, string string_4, string string_5, string string_6, string string_7)
        {
            this.AddWare(string_0, string_1, string_2, Convert.ToDouble(string_3), Convert.ToDouble(string_4), Convert.ToDouble(string_5), Convert.ToDouble(string_6), Convert.ToDouble(string_7));
        }

        public void BindData()
        {
            if (this._FPLX == "s")
            {
                this.lab_title.Text = "增值税专用发票";
            }
            else if (this._FPLX == "c")
            {
                this.lab_title.Text = "增值税普通发票";
            }
            this.XFMC.Text = this._XFMC;
            this.XFMC.Text = this._XFMC;
            this.XFSH.Text = this._XFSH;
            this.GFMC.Text = this._GFMC;
            this.GFSH.Text = this._GFSH;
            this.GFYHZH.Text = this._GFYHZH;
            this.GFDZDH.Text = this._GFDZDH;
            this.XFDZDH.Text = this._XFDZDH;
            this.XFYHZH.Text = this._XFYHZH;
            this.BZ.Text = this._BZ;
            this.SKR.Text = this._SKR;
            this.FHR.Text = this._FHR;
            this.KPRQ.Text = this._KPRQ;
            this.KPR.Text = this._KPR;
            this.TaxTotal.Text = this._TaxTotal.ToString("C");
            this.AmountTotal.Text = this._AmountTotal.ToString("C");
            this.lab_fpdm.Text = this._FPDM;
            this.lab_fphm.Text = this._FPHM.PadLeft(8, '0');
            decimal num2 = this._TaxTotal + this._AmountTotal;
            this.lab_hj_dx.Text = "㊣ " + ToolUtil.RMBToDaXie(num2);
            this.lab_hj_xx.Text = num2.ToString("C");
            for (int i = 0; i < this.list_0.Count; i++)
            {
                switch (i)
                {
                    case 0:
                        this.SPMC1.Text = this.list_0[i][0];
                        this.GGXH1.Text = this.list_0[i][1];
                        this.DW1.Text = this.list_0[i][2];
                        this.SL1.Text = this.list_0[i][3];
                        this.DJ1.Text = this.list_0[i][4];
                        this.JE1.Text = this.list_0[i][5];
                        this.SE1.Text = this.list_0[i][6];
                        this.SLV1.Text = this.list_0[i][7];
                        break;

                    case 1:
                        this.SPMC2.Text = this.list_0[i][0];
                        this.GGXH2.Text = this.list_0[i][1];
                        this.DW2.Text = this.list_0[i][2];
                        this.SL2.Text = this.list_0[i][3];
                        this.DJ2.Text = this.list_0[i][4];
                        this.JE2.Text = this.list_0[i][5];
                        this.SE2.Text = this.list_0[i][6];
                        this.SLV2.Text = this.list_0[i][7];
                        break;

                    case 2:
                        this.SPMC3.Text = this.list_0[i][0];
                        this.GGXH3.Text = this.list_0[i][1];
                        this.DW3.Text = this.list_0[i][2];
                        this.SL3.Text = this.list_0[i][3];
                        this.DJ3.Text = this.list_0[i][4];
                        this.JE3.Text = this.list_0[i][5];
                        this.SE3.Text = this.list_0[i][6];
                        this.SLV3.Text = this.list_0[i][7];
                        break;

                    case 3:
                        this.SPMC4.Text = this.list_0[i][0];
                        this.GGXH4.Text = this.list_0[i][1];
                        this.DW4.Text = this.list_0[i][2];
                        this.SL4.Text = this.list_0[i][3];
                        this.DJ4.Text = this.list_0[i][4];
                        this.JE4.Text = this.list_0[i][5];
                        this.SE4.Text = this.list_0[i][6];
                        this.SLV4.Text = this.list_0[i][7];
                        break;

                    case 4:
                        this.SPMC5.Text = this.list_0[i][0];
                        this.GGXH5.Text = this.list_0[i][1];
                        this.DW5.Text = this.list_0[i][2];
                        this.SL5.Text = this.list_0[i][3];
                        this.DJ5.Text = this.list_0[i][4];
                        this.JE5.Text = this.list_0[i][5];
                        this.SE5.Text = this.list_0[i][6];
                        this.SLV5.Text = this.list_0[i][7];
                        break;

                    case 5:
                        this.SPMC6.Text = this.list_0[i][0];
                        this.GGXH6.Text = this.list_0[i][1];
                        this.DW6.Text = this.list_0[i][2];
                        this.SL6.Text = this.list_0[i][3];
                        this.DJ6.Text = this.list_0[i][4];
                        this.JE6.Text = this.list_0[i][5];
                        this.SE6.Text = this.list_0[i][6];
                        this.SLV6.Text = this.list_0[i][7];
                        break;

                    case 6:
                        this.SPMC7.Text = this.list_0[i][0];
                        this.GGXH7.Text = this.list_0[i][1];
                        this.DW7.Text = this.list_0[i][2];
                        this.SL7.Text = this.list_0[i][3];
                        this.DJ7.Text = this.list_0[i][4];
                        this.JE7.Text = this.list_0[i][5];
                        this.SE7.Text = this.list_0[i][6];
                        this.SLV7.Text = this.list_0[i][7];
                        break;
                }
            }
            this.ClearWareList();
        }

        public void ClearWareList()
        {
            this.list_0.Clear();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.KPRQ = new AisinoLBL();
            this.label1 = new AisinoLBL();
            this.lab_title = new AisinoLBL();
            this.label5 = new AisinoLBL();
            this.lab_hj_dx = new AisinoLBL();
            this.label25 = new AisinoLBL();
            this.KPR = new AisinoLBL();
            this.label28 = new AisinoLBL();
            this.label17 = new AisinoLBL();
            this.label27 = new AisinoLBL();
            this.label26 = new AisinoLBL();
            this.label21 = new AisinoLBL();
            this.label20 = new AisinoLBL();
            this.label19 = new AisinoLBL();
            this.lab_hj_jshj = new AisinoLBL();
            this.label18 = new AisinoLBL();
            this.label13 = new AisinoLBL();
            this.label16 = new AisinoLBL();
            this.label8 = new AisinoLBL();
            this.label4 = new AisinoLBL();
            this.label9 = new AisinoLBL();
            this.label10 = new AisinoLBL();
            this.label11 = new AisinoLBL();
            this.label7 = new AisinoLBL();
            this.TaxTotal = new AisinoLBL();
            this.AmountTotal = new AisinoLBL();
            this.label12 = new AisinoLBL();
            this.label24 = new AisinoLBL();
            this.label30 = new AisinoLBL();
            this.label32 = new AisinoLBL();
            this.label29 = new AisinoLBL();
            this.label6 = new AisinoLBL();
            this.label22 = new AisinoLBL();
            this.label31 = new AisinoLBL();
            this.label23 = new AisinoLBL();
            this.SPMC1 = new AisinoLBL();
            this.SPMC2 = new AisinoLBL();
            this.SPMC3 = new AisinoLBL();
            this.SPMC4 = new AisinoLBL();
            this.SPMC6 = new AisinoLBL();
            this.SPMC7 = new AisinoLBL();
            this.SPMC5 = new AisinoLBL();
            this.GGXH1 = new AisinoLBL();
            this.GGXH2 = new AisinoLBL();
            this.GGXH3 = new AisinoLBL();
            this.GGXH4 = new AisinoLBL();
            this.GGXH7 = new AisinoLBL();
            this.GGXH6 = new AisinoLBL();
            this.GGXH5 = new AisinoLBL();
            this.DW1 = new AisinoLBL();
            this.DW2 = new AisinoLBL();
            this.DW4 = new AisinoLBL();
            this.DW5 = new AisinoLBL();
            this.DW6 = new AisinoLBL();
            this.DW7 = new AisinoLBL();
            this.DW3 = new AisinoLBL();
            this.SL7 = new AisinoLBL();
            this.SL6 = new AisinoLBL();
            this.SL5 = new AisinoLBL();
            this.SL4 = new AisinoLBL();
            this.SL3 = new AisinoLBL();
            this.SL2 = new AisinoLBL();
            this.SL1 = new AisinoLBL();
            this.DJ7 = new AisinoLBL();
            this.DJ6 = new AisinoLBL();
            this.DJ5 = new AisinoLBL();
            this.DJ4 = new AisinoLBL();
            this.DJ3 = new AisinoLBL();
            this.DJ2 = new AisinoLBL();
            this.DJ1 = new AisinoLBL();
            this.JE7 = new AisinoLBL();
            this.JE6 = new AisinoLBL();
            this.JE5 = new AisinoLBL();
            this.JE4 = new AisinoLBL();
            this.JE3 = new AisinoLBL();
            this.JE2 = new AisinoLBL();
            this.JE1 = new AisinoLBL();
            this.SE7 = new AisinoLBL();
            this.SE6 = new AisinoLBL();
            this.SE5 = new AisinoLBL();
            this.SE4 = new AisinoLBL();
            this.SE3 = new AisinoLBL();
            this.SE2 = new AisinoLBL();
            this.SE1 = new AisinoLBL();
            this.SLV1 = new AisinoLBL();
            this.SLV2 = new AisinoLBL();
            this.SLV4 = new AisinoLBL();
            this.SLV3 = new AisinoLBL();
            this.SLV7 = new AisinoLBL();
            this.SLV6 = new AisinoLBL();
            this.SLV5 = new AisinoLBL();
            this.XFMC = new AisinoLBL();
            this.XFSH = new AisinoLBL();
            this.GFMC = new AisinoLBL();
            this.GFSH = new AisinoLBL();
            this.GFYHZH = new AisinoLBL();
            this.GFDZDH = new AisinoLBL();
            this.XFDZDH = new AisinoLBL();
            this.XFYHZH = new AisinoLBL();
            this.BZ = new AisinoLBL();
            this.SKR = new AisinoLBL();
            this.FHR = new AisinoLBL();
            this.lab_fphm = new AisinoLBL();
            this.lab_fpdm = new AisinoLBL();
            this.label3 = new AisinoLBL();
            this.invoicePanelLt1 = new InvoicePanelLt();
            this.lab_hj_xx = new AisinoLBL();
            this.label2 = new AisinoLBL();
            base.SuspendLayout();
            this.KPRQ.AutoSize = true;
            this.KPRQ.BackColor = SystemColors.ControlLightLight;
            this.KPRQ.Font = new Font("宋体", 9f);
            this.KPRQ.Location = new Point(0x344, 0x47);
            this.KPRQ.Name = "KPRQ";
            this.KPRQ.Size = new Size(0x29, 12);
            this.KPRQ.TabIndex = 0x66;
            this.KPRQ.Text = "年月日";
            this.label1.AutoSize = true;
            this.label1.BackColor = SystemColors.ControlLightLight;
            this.label1.Font = new Font("楷体_GB2312", 9f);
            this.label1.Location = new Point(0x2db, 0x47);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x35, 12);
            this.label1.TabIndex = 0x65;
            this.label1.Text = "开票日期";
            this.lab_title.Anchor = AnchorStyles.Top;
            this.lab_title.AutoSize = true;
            this.lab_title.BackColor = SystemColors.ControlLightLight;
            this.lab_title.Font = new Font("楷体_GB2312", 16f, FontStyle.Bold);
            this.lab_title.ForeColor = Color.Blue;
            this.lab_title.Location = new Point(410, 12);
            this.lab_title.Name = "lab_title";
            this.lab_title.Size = new Size(0xab, 0x16);
            this.lab_title.TabIndex = 100;
            this.lab_title.Text = "增值税专用发票";
            this.label5.AutoSize = true;
            this.label5.BackColor = SystemColors.ControlLightLight;
            this.label5.Font = new Font("楷体_GB2312", 9f);
            this.label5.Location = new Point(0x2c1, 0x1c3);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x65, 12);
            this.label5.TabIndex = 0x63;
            this.label5.Text = "销货单位：（章）";
            this.lab_hj_dx.AutoSize = true;
            this.lab_hj_dx.BackColor = SystemColors.ControlLightLight;
            this.lab_hj_dx.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_hj_dx.Location = new Point(0x145, 340);
            this.lab_hj_dx.Name = "lab_hj_dx";
            this.lab_hj_dx.Size = new Size(0x11, 12);
            this.lab_hj_dx.TabIndex = 90;
            this.lab_hj_dx.Text = "零";
            this.label25.AutoSize = true;
            this.label25.BackColor = SystemColors.ControlLightLight;
            this.label25.Font = new Font("楷体_GB2312", 9f);
            this.label25.Location = new Point(0x234, 0x171);
            this.label25.Name = "label25";
            this.label25.Size = new Size(0x11, 60);
            this.label25.TabIndex = 0x55;
            this.label25.Text = "备\r\n\r\n\r\n\r\n注";
            this.KPR.AutoSize = true;
            this.KPR.BackColor = SystemColors.ControlLightLight;
            this.KPR.Location = new Point(540, 0x1c3);
            this.KPR.Name = "KPR";
            this.KPR.Size = new Size(0x23, 12);
            this.KPR.TabIndex = 0x62;
            this.KPR.Text = "admin";
            this.label28.AutoSize = true;
            this.label28.BackColor = SystemColors.ControlLightLight;
            this.label28.Font = new Font("楷体_GB2312", 9f);
            this.label28.Location = new Point(0x1e1, 0x1c3);
            this.label28.Name = "label28";
            this.label28.Size = new Size(0x35, 12);
            this.label28.TabIndex = 0x61;
            this.label28.Text = "开票人：";
            this.label17.AutoSize = true;
            this.label17.BackColor = SystemColors.ControlLightLight;
            this.label17.Font = new Font("楷体_GB2312", 9f);
            this.label17.Location = new Point(0x54, 0x174);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x11, 0x30);
            this.label17.TabIndex = 0x56;
            this.label17.Text = "销\r\n货\r\n单\r\n位";
            this.label27.AutoSize = true;
            this.label27.BackColor = SystemColors.ControlLightLight;
            this.label27.Font = new Font("楷体_GB2312", 9f);
            this.label27.Location = new Point(0x151, 0x1c3);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x35, 12);
            this.label27.TabIndex = 0x60;
            this.label27.Text = "复核人：";
            this.label26.AutoSize = true;
            this.label26.BackColor = SystemColors.ControlLightLight;
            this.label26.Font = new Font("楷体_GB2312", 9f);
            this.label26.Location = new Point(0x5d, 0x1c3);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x35, 12);
            this.label26.TabIndex = 0x5f;
            this.label26.Text = "收款人：";
            this.label21.AutoSize = true;
            this.label21.BackColor = SystemColors.ControlLightLight;
            this.label21.Font = new Font("楷体_GB2312", 9f);
            this.label21.Location = new Point(0x81, 0x1a1);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x59, 12);
            this.label21.TabIndex = 0x5e;
            this.label21.Text = "开户行及账号：";
            this.label20.AutoSize = true;
            this.label20.BackColor = SystemColors.ControlLightLight;
            this.label20.Font = new Font("楷体_GB2312", 9f);
            this.label20.Location = new Point(0x81, 0x18e);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x59, 12);
            this.label20.TabIndex = 0x5d;
            this.label20.Text = "地 址、电 话：";
            this.label19.AutoSize = true;
            this.label19.BackColor = SystemColors.ControlLightLight;
            this.label19.Font = new Font("楷体_GB2312", 9f);
            this.label19.Location = new Point(0x81, 0x17b);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x59, 12);
            this.label19.TabIndex = 0x5c;
            this.label19.Text = "纳税人识别号：";
            this.lab_hj_jshj.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.lab_hj_jshj.AutoSize = true;
            this.lab_hj_jshj.BackColor = SystemColors.ControlLightLight;
            this.lab_hj_jshj.Location = new Point(0x48e, 0x1ba);
            this.lab_hj_jshj.Name = "lab_hj_jshj";
            this.lab_hj_jshj.RightToLeft = RightToLeft.No;
            this.lab_hj_jshj.Size = new Size(11, 12);
            this.lab_hj_jshj.TabIndex = 0x59;
            this.lab_hj_jshj.Text = "0";
            this.label18.AutoSize = true;
            this.label18.BackColor = SystemColors.ControlLightLight;
            this.label18.Font = new Font("楷体_GB2312", 9f);
            this.label18.Location = new Point(0x81, 360);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x59, 12);
            this.label18.TabIndex = 0x5b;
            this.label18.Text = "名        称：";
            this.label13.AutoSize = true;
            this.label13.BackColor = SystemColors.ControlLightLight;
            this.label13.Font = new Font("楷体_GB2312", 9f);
            this.label13.Location = new Point(0x75, 340);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x65, 12);
            this.label13.TabIndex = 0x58;
            this.label13.Text = "价税合计(大写)：";
            this.label16.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.label16.AutoSize = true;
            this.label16.BackColor = SystemColors.ControlLightLight;
            this.label16.Font = new Font("宋体", 10f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label16.Location = new Point(0x3ea, 0x1ba);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x31, 14);
            this.label16.TabIndex = 0x57;
            this.label16.Text = "(小写)";
            this.label8.AutoSize = true;
            this.label8.BackColor = SystemColors.ControlLightLight;
            this.label8.Font = new Font("楷体_GB2312", 9f);
            this.label8.Location = new Point(0x81, 0x5d);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x59, 12);
            this.label8.TabIndex = 0x51;
            this.label8.Text = "名        称：";
            this.label4.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.label4.AutoSize = true;
            this.label4.BackColor = SystemColors.ControlLightLight;
            this.label4.Font = new Font("楷体_GB2312", 9f);
            this.label4.Location = new Point(0x234, 0x5d);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x11, 60);
            this.label4.TabIndex = 0x4f;
            this.label4.Text = "密\r\n\r\n码\r\n\r\n区";
            this.label9.AutoSize = true;
            this.label9.BackColor = SystemColors.ControlLightLight;
            this.label9.Font = new Font("楷体_GB2312", 9f);
            this.label9.Location = new Point(0x81, 0x6d);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x59, 12);
            this.label9.TabIndex = 0x52;
            this.label9.Text = "纳税人识别号：";
            this.label10.AutoSize = true;
            this.label10.BackColor = SystemColors.ControlLightLight;
            this.label10.Font = new Font("楷体_GB2312", 9f);
            this.label10.Location = new Point(0x81, 0x7d);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x59, 12);
            this.label10.TabIndex = 0x53;
            this.label10.Text = "地 址、电 话：";
            this.label11.AutoSize = true;
            this.label11.BackColor = SystemColors.ControlLightLight;
            this.label11.Font = new Font("楷体_GB2312", 9f);
            this.label11.Location = new Point(0x81, 0x8d);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x59, 12);
            this.label11.TabIndex = 0x54;
            this.label11.Text = "开户行及账号：";
            this.label7.AutoSize = true;
            this.label7.BackColor = SystemColors.ControlLightLight;
            this.label7.Font = new Font("楷体_GB2312", 9f);
            this.label7.Location = new Point(0x54, 0x66);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x11, 0x30);
            this.label7.TabIndex = 80;
            this.label7.Text = "购\r\n货\r\n单\r\n位";
            this.TaxTotal.AutoSize = true;
            this.TaxTotal.BackColor = SystemColors.ControlLightLight;
            this.TaxTotal.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.TaxTotal.Location = new Point(0x314, 0x13e);
            this.TaxTotal.Name = "TaxTotal";
            this.TaxTotal.Size = new Size(0x29, 12);
            this.TaxTotal.TabIndex = 0x4e;
            this.TaxTotal.Text = "税额：";
            this.AmountTotal.AutoSize = true;
            this.AmountTotal.BackColor = SystemColors.ControlLightLight;
            this.AmountTotal.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.AmountTotal.Location = new Point(0x268, 0x13e);
            this.AmountTotal.Name = "AmountTotal";
            this.AmountTotal.Size = new Size(0x29, 12);
            this.AmountTotal.TabIndex = 0x4d;
            this.AmountTotal.Text = "金额：";
            this.label12.AutoSize = true;
            this.label12.BackColor = SystemColors.ControlLightLight;
            this.label12.Font = new Font("楷体_GB2312", 9f);
            this.label12.Location = new Point(0x75, 0x13e);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x41, 12);
            this.label12.TabIndex = 0x4c;
            this.label12.Text = "合      计";
            this.label24.AutoSize = true;
            this.label24.BackColor = SystemColors.ControlLightLight;
            this.label24.Font = new Font("楷体_GB2312", 9f);
            this.label24.Location = new Point(0x1b9, 0xa9);
            this.label24.Name = "label24";
            this.label24.Size = new Size(0x1d, 12);
            this.label24.TabIndex = 0x4b;
            this.label24.Text = "数量";
            this.label30.AutoSize = true;
            this.label30.BackColor = SystemColors.ControlLightLight;
            this.label30.Font = new Font("楷体_GB2312", 9f);
            this.label30.Location = new Point(0x27a, 0xa9);
            this.label30.Name = "label30";
            this.label30.Size = new Size(0x1d, 12);
            this.label30.TabIndex = 0x48;
            this.label30.Text = "金额";
            this.label32.AutoSize = true;
            this.label32.BackColor = SystemColors.ControlLightLight;
            this.label32.Font = new Font("楷体_GB2312", 9f);
            this.label32.Location = new Point(0x2db, 0xa9);
            this.label32.Name = "label32";
            this.label32.Size = new Size(0x1d, 12);
            this.label32.TabIndex = 0x4a;
            this.label32.Text = "税率";
            this.label29.AutoSize = true;
            this.label29.BackColor = SystemColors.ControlLightLight;
            this.label29.Font = new Font("楷体_GB2312", 9f);
            this.label29.Location = new Point(0x20e, 0xa9);
            this.label29.Name = "label29";
            this.label29.Size = new Size(0x1d, 12);
            this.label29.TabIndex = 0x49;
            this.label29.Text = "单价";
            this.label6.AutoSize = true;
            this.label6.BackColor = SystemColors.ControlLightLight;
            this.label6.Font = new Font("楷体_GB2312", 9f);
            this.label6.Location = new Point(0x75, 0xa9);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x71, 12);
            this.label6.TabIndex = 0x44;
            this.label6.Text = "货物或应税劳务名称";
            this.label22.AutoSize = true;
            this.label22.BackColor = SystemColors.ControlLightLight;
            this.label22.Font = new Font("楷体_GB2312", 9f);
            this.label22.Location = new Point(0x139, 0xa9);
            this.label22.Name = "label22";
            this.label22.Size = new Size(0x35, 12);
            this.label22.TabIndex = 70;
            this.label22.Text = "规格型号";
            this.label31.AutoSize = true;
            this.label31.BackColor = SystemColors.ControlLightLight;
            this.label31.Font = new Font("楷体_GB2312", 9f);
            this.label31.Location = new Point(0x32f, 0xa9);
            this.label31.Name = "label31";
            this.label31.Size = new Size(0x1d, 12);
            this.label31.TabIndex = 0x47;
            this.label31.Text = "税额";
            this.label23.AutoSize = true;
            this.label23.BackColor = SystemColors.ControlLightLight;
            this.label23.Font = new Font("楷体_GB2312", 9f);
            this.label23.Location = new Point(0x18d, 0xa9);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x1d, 12);
            this.label23.TabIndex = 0x45;
            this.label23.Text = "单位";
            this.SPMC1.AutoSize = true;
            this.SPMC1.Location = new Point(0x54, 0xbc);
            this.SPMC1.Name = "SPMC1";
            this.SPMC1.Size = new Size(0x23, 12);
            this.SPMC1.TabIndex = 0x67;
            this.SPMC1.Text = "SPMC1";
            this.SPMC2.AutoSize = true;
            this.SPMC2.Location = new Point(0x54, 0xcf);
            this.SPMC2.Name = "SPMC2";
            this.SPMC2.Size = new Size(0x23, 12);
            this.SPMC2.TabIndex = 0x68;
            this.SPMC2.Text = "SPMC2";
            this.SPMC3.AutoSize = true;
            this.SPMC3.Location = new Point(0x54, 0xe2);
            this.SPMC3.Name = "SPMC3";
            this.SPMC3.Size = new Size(0x23, 12);
            this.SPMC3.TabIndex = 0x69;
            this.SPMC3.Text = "SPMC3";
            this.SPMC4.AutoSize = true;
            this.SPMC4.Location = new Point(0x54, 0xf5);
            this.SPMC4.Name = "SPMC4";
            this.SPMC4.Size = new Size(0x23, 12);
            this.SPMC4.TabIndex = 0x6a;
            this.SPMC4.Text = "SPMC4";
            this.SPMC6.AutoSize = true;
            this.SPMC6.Location = new Point(0x54, 0x11b);
            this.SPMC6.Name = "SPMC6";
            this.SPMC6.Size = new Size(0x23, 12);
            this.SPMC6.TabIndex = 0x6b;
            this.SPMC6.Text = "SPMC6";
            this.SPMC7.AutoSize = true;
            this.SPMC7.Location = new Point(0x54, 0x12e);
            this.SPMC7.Name = "SPMC7";
            this.SPMC7.Size = new Size(0x23, 12);
            this.SPMC7.TabIndex = 0x6c;
            this.SPMC7.Text = "SPMC7";
            this.SPMC5.AutoSize = true;
            this.SPMC5.Location = new Point(0x54, 0x108);
            this.SPMC5.Name = "SPMC5";
            this.SPMC5.Size = new Size(0x23, 12);
            this.SPMC5.TabIndex = 0x6d;
            this.SPMC5.Text = "SPMC5";
            this.GGXH1.AutoSize = true;
            this.GGXH1.Location = new Point(0x12d, 0xbd);
            this.GGXH1.Name = "GGXH1";
            this.GGXH1.Size = new Size(0x23, 12);
            this.GGXH1.TabIndex = 110;
            this.GGXH1.Text = "GGXH1";
            this.GGXH2.AutoSize = true;
            this.GGXH2.Location = new Point(0x12d, 0xd0);
            this.GGXH2.Name = "GGXH2";
            this.GGXH2.Size = new Size(0x29, 12);
            this.GGXH2.TabIndex = 0x6f;
            this.GGXH2.Text = "label3";
            this.GGXH3.AutoSize = true;
            this.GGXH3.Location = new Point(0x12d, 0xe3);
            this.GGXH3.Name = "GGXH3";
            this.GGXH3.Size = new Size(0x2f, 12);
            this.GGXH3.TabIndex = 0x70;
            this.GGXH3.Text = "label14";
            this.GGXH4.AutoSize = true;
            this.GGXH4.Location = new Point(0x12d, 0xf6);
            this.GGXH4.Name = "GGXH4";
            this.GGXH4.Size = new Size(0x2f, 12);
            this.GGXH4.TabIndex = 0x71;
            this.GGXH4.Text = "label15";
            this.GGXH7.AutoSize = true;
            this.GGXH7.Location = new Point(0x12d, 0x12f);
            this.GGXH7.Name = "GGXH7";
            this.GGXH7.Size = new Size(0x2f, 12);
            this.GGXH7.TabIndex = 0x74;
            this.GGXH7.Text = "label33";
            this.GGXH6.AutoSize = true;
            this.GGXH6.Location = new Point(0x12d, 0x11c);
            this.GGXH6.Name = "GGXH6";
            this.GGXH6.Size = new Size(0x2f, 12);
            this.GGXH6.TabIndex = 0x73;
            this.GGXH6.Text = "label34";
            this.GGXH5.AutoSize = true;
            this.GGXH5.Location = new Point(0x12d, 0x108);
            this.GGXH5.Name = "GGXH5";
            this.GGXH5.Size = new Size(0x2f, 12);
            this.GGXH5.TabIndex = 0x72;
            this.GGXH5.Text = "label35";
            this.DW1.AutoSize = true;
            this.DW1.Location = new Point(0x18d, 0xbc);
            this.DW1.Name = "DW1";
            this.DW1.Size = new Size(0x11, 12);
            this.DW1.TabIndex = 0x75;
            this.DW1.Text = "件";
            this.DW2.AutoSize = true;
            this.DW2.Location = new Point(0x18d, 0xd0);
            this.DW2.Name = "DW2";
            this.DW2.Size = new Size(0x11, 12);
            this.DW2.TabIndex = 0x76;
            this.DW2.Text = "件";
            this.DW4.AutoSize = true;
            this.DW4.Location = new Point(0x18d, 0xf5);
            this.DW4.Name = "DW4";
            this.DW4.Size = new Size(0x11, 12);
            this.DW4.TabIndex = 0x77;
            this.DW4.Text = "件";
            this.DW5.AutoSize = true;
            this.DW5.Location = new Point(0x18d, 0x108);
            this.DW5.Name = "DW5";
            this.DW5.Size = new Size(0x11, 12);
            this.DW5.TabIndex = 120;
            this.DW5.Text = "件";
            this.DW6.AutoSize = true;
            this.DW6.Location = new Point(0x18d, 0x11b);
            this.DW6.Name = "DW6";
            this.DW6.Size = new Size(0x11, 12);
            this.DW6.TabIndex = 0x79;
            this.DW6.Text = "件";
            this.DW7.AutoSize = true;
            this.DW7.Location = new Point(0x18d, 0x12e);
            this.DW7.Name = "DW7";
            this.DW7.Size = new Size(0x11, 12);
            this.DW7.TabIndex = 0x7a;
            this.DW7.Text = "件";
            this.DW3.AutoSize = true;
            this.DW3.Location = new Point(0x18d, 0xe3);
            this.DW3.Name = "DW3";
            this.DW3.Size = new Size(0x11, 12);
            this.DW3.TabIndex = 0x7b;
            this.DW3.Text = "件";
            this.SL7.AutoSize = true;
            this.SL7.Location = new Point(0x1b9, 0x12f);
            this.SL7.Name = "SL7";
            this.SL7.Size = new Size(0x2f, 12);
            this.SL7.TabIndex = 130;
            this.SL7.Text = "label33";
            this.SL6.AutoSize = true;
            this.SL6.Location = new Point(0x1b9, 0x11c);
            this.SL6.Name = "SL6";
            this.SL6.Size = new Size(0x2f, 12);
            this.SL6.TabIndex = 0x81;
            this.SL6.Text = "label34";
            this.SL5.AutoSize = true;
            this.SL5.Location = new Point(0x1b9, 0x108);
            this.SL5.Name = "SL5";
            this.SL5.Size = new Size(0x2f, 12);
            this.SL5.TabIndex = 0x80;
            this.SL5.Text = "label35";
            this.SL4.AutoSize = true;
            this.SL4.Location = new Point(0x1b9, 0xf6);
            this.SL4.Name = "SL4";
            this.SL4.Size = new Size(0x2f, 12);
            this.SL4.TabIndex = 0x7f;
            this.SL4.Text = "label15";
            this.SL3.AutoSize = true;
            this.SL3.Location = new Point(0x1b9, 0xe3);
            this.SL3.Name = "SL3";
            this.SL3.Size = new Size(0x2f, 12);
            this.SL3.TabIndex = 0x7e;
            this.SL3.Text = "label14";
            this.SL2.AutoSize = true;
            this.SL2.Location = new Point(0x1b9, 0xd0);
            this.SL2.Name = "SL2";
            this.SL2.Size = new Size(0x29, 12);
            this.SL2.TabIndex = 0x7d;
            this.SL2.Text = "label3";
            this.SL1.AutoSize = true;
            this.SL1.Location = new Point(0x1b9, 0xbd);
            this.SL1.Name = "SL1";
            this.SL1.Size = new Size(0x2f, 12);
            this.SL1.TabIndex = 0x7c;
            this.SL1.Text = "label36";
            this.DJ7.AutoSize = true;
            this.DJ7.Location = new Point(0x20e, 0x12f);
            this.DJ7.Name = "DJ7";
            this.DJ7.Size = new Size(0x2f, 12);
            this.DJ7.TabIndex = 0x89;
            this.DJ7.Text = "label33";
            this.DJ6.AutoSize = true;
            this.DJ6.Location = new Point(0x20e, 0x11c);
            this.DJ6.Name = "DJ6";
            this.DJ6.Size = new Size(0x2f, 12);
            this.DJ6.TabIndex = 0x88;
            this.DJ6.Text = "label34";
            this.DJ5.AutoSize = true;
            this.DJ5.Location = new Point(0x20e, 0x108);
            this.DJ5.Name = "DJ5";
            this.DJ5.Size = new Size(0x2f, 12);
            this.DJ5.TabIndex = 0x87;
            this.DJ5.Text = "label35";
            this.DJ4.AutoSize = true;
            this.DJ4.Location = new Point(0x20e, 0xf6);
            this.DJ4.Name = "DJ4";
            this.DJ4.Size = new Size(0x2f, 12);
            this.DJ4.TabIndex = 0x86;
            this.DJ4.Text = "label15";
            this.DJ3.AutoSize = true;
            this.DJ3.Location = new Point(0x20e, 0xe3);
            this.DJ3.Name = "DJ3";
            this.DJ3.Size = new Size(0x2f, 12);
            this.DJ3.TabIndex = 0x85;
            this.DJ3.Text = "label14";
            this.DJ2.AutoSize = true;
            this.DJ2.Location = new Point(0x20e, 0xd0);
            this.DJ2.Name = "DJ2";
            this.DJ2.Size = new Size(0x29, 12);
            this.DJ2.TabIndex = 0x84;
            this.DJ2.Text = "label3";
            this.DJ1.AutoSize = true;
            this.DJ1.Location = new Point(0x20e, 0xbd);
            this.DJ1.Name = "DJ1";
            this.DJ1.Size = new Size(0x2f, 12);
            this.DJ1.TabIndex = 0x83;
            this.DJ1.Text = "label43";
            this.JE7.AutoSize = true;
            this.JE7.Location = new Point(0x29c, 0x12f);
            this.JE7.Name = "JE7";
            this.JE7.Size = new Size(0x2f, 12);
            this.JE7.TabIndex = 0x90;
            this.JE7.Text = "label33";
            this.JE7.TextAlign = ContentAlignment.TopRight;
            this.JE6.AutoSize = true;
            this.JE6.Location = new Point(0x29c, 0x11c);
            this.JE6.Name = "JE6";
            this.JE6.Size = new Size(0x2f, 12);
            this.JE6.TabIndex = 0x8f;
            this.JE6.Text = "label34";
            this.JE6.TextAlign = ContentAlignment.TopRight;
            this.JE5.AutoSize = true;
            this.JE5.Location = new Point(0x29c, 0x108);
            this.JE5.Name = "JE5";
            this.JE5.Size = new Size(0x2f, 12);
            this.JE5.TabIndex = 0x8e;
            this.JE5.Text = "label35";
            this.JE5.TextAlign = ContentAlignment.TopRight;
            this.JE4.AutoSize = true;
            this.JE4.Location = new Point(0x29c, 0xf6);
            this.JE4.Name = "JE4";
            this.JE4.Size = new Size(0x2f, 12);
            this.JE4.TabIndex = 0x8d;
            this.JE4.Text = "label15";
            this.JE4.TextAlign = ContentAlignment.TopRight;
            this.JE3.AutoSize = true;
            this.JE3.Location = new Point(0x29c, 0xe3);
            this.JE3.Name = "JE3";
            this.JE3.Size = new Size(0x2f, 12);
            this.JE3.TabIndex = 140;
            this.JE3.Text = "label14";
            this.JE3.TextAlign = ContentAlignment.TopRight;
            this.JE2.AutoSize = true;
            this.JE2.Location = new Point(0x2a2, 0xd0);
            this.JE2.Name = "JE2";
            this.JE2.Size = new Size(0x29, 12);
            this.JE2.TabIndex = 0x8b;
            this.JE2.Text = "label3";
            this.JE2.TextAlign = ContentAlignment.TopRight;
            this.JE1.AutoSize = true;
            this.JE1.Location = new Point(0x29c, 0xbc);
            this.JE1.Name = "JE1";
            this.JE1.Size = new Size(0x2f, 12);
            this.JE1.TabIndex = 0x8a;
            this.JE1.Text = "label50";
            this.JE1.TextAlign = ContentAlignment.TopRight;
            this.SE7.AutoSize = true;
            this.SE7.Location = new Point(0x34e, 0x12f);
            this.SE7.Name = "SE7";
            this.SE7.Size = new Size(0x2f, 12);
            this.SE7.TabIndex = 0x9e;
            this.SE7.Text = "label33";
            this.SE7.TextAlign = ContentAlignment.TopRight;
            this.SE6.AutoSize = true;
            this.SE6.Location = new Point(0x34e, 0x11c);
            this.SE6.Name = "SE6";
            this.SE6.Size = new Size(0x2f, 12);
            this.SE6.TabIndex = 0x9d;
            this.SE6.Text = "label34";
            this.SE6.TextAlign = ContentAlignment.TopRight;
            this.SE5.AutoSize = true;
            this.SE5.Location = new Point(0x34e, 0x108);
            this.SE5.Name = "SE5";
            this.SE5.Size = new Size(0x2f, 12);
            this.SE5.TabIndex = 0x9c;
            this.SE5.Text = "label35";
            this.SE5.TextAlign = ContentAlignment.TopRight;
            this.SE4.AutoSize = true;
            this.SE4.Location = new Point(0x34e, 0xf6);
            this.SE4.Name = "SE4";
            this.SE4.Size = new Size(0x2f, 12);
            this.SE4.TabIndex = 0x9b;
            this.SE4.Text = "label15";
            this.SE4.TextAlign = ContentAlignment.TopRight;
            this.SE3.AutoSize = true;
            this.SE3.Location = new Point(0x34e, 0xe3);
            this.SE3.Name = "SE3";
            this.SE3.Size = new Size(0x2f, 12);
            this.SE3.TabIndex = 0x9a;
            this.SE3.Text = "label14";
            this.SE3.TextAlign = ContentAlignment.TopRight;
            this.SE2.AutoSize = true;
            this.SE2.Location = new Point(0x354, 0xd0);
            this.SE2.Name = "SE2";
            this.SE2.Size = new Size(0x29, 12);
            this.SE2.TabIndex = 0x99;
            this.SE2.Text = "label3";
            this.SE2.TextAlign = ContentAlignment.TopRight;
            this.SE1.AutoSize = true;
            this.SE1.Location = new Point(0x34e, 0xbd);
            this.SE1.Name = "SE1";
            this.SE1.Size = new Size(0x2f, 12);
            this.SE1.TabIndex = 0x98;
            this.SE1.Text = "label64";
            this.SE1.TextAlign = ContentAlignment.TopRight;
            this.SLV1.AutoSize = true;
            this.SLV1.Location = new Point(0x2db, 0xbd);
            this.SLV1.Name = "SLV1";
            this.SLV1.Size = new Size(0x17, 12);
            this.SLV1.TabIndex = 0x9f;
            this.SLV1.Text = "17%";
            this.SLV2.AutoSize = true;
            this.SLV2.Location = new Point(0x2db, 0xd0);
            this.SLV2.Name = "SLV2";
            this.SLV2.Size = new Size(0x17, 12);
            this.SLV2.TabIndex = 160;
            this.SLV2.Text = "17%";
            this.SLV4.AutoSize = true;
            this.SLV4.Location = new Point(0x2db, 0xf6);
            this.SLV4.Name = "SLV4";
            this.SLV4.Size = new Size(0x17, 12);
            this.SLV4.TabIndex = 0xa2;
            this.SLV4.Text = "17%";
            this.SLV3.AutoSize = true;
            this.SLV3.Location = new Point(0x2db, 0xe3);
            this.SLV3.Name = "SLV3";
            this.SLV3.Size = new Size(0x17, 12);
            this.SLV3.TabIndex = 0xa1;
            this.SLV3.Text = "17%";
            this.SLV7.AutoSize = true;
            this.SLV7.Location = new Point(0x2db, 0x12e);
            this.SLV7.Name = "SLV7";
            this.SLV7.Size = new Size(0x17, 12);
            this.SLV7.TabIndex = 0xa5;
            this.SLV7.Text = "17%";
            this.SLV6.AutoSize = true;
            this.SLV6.Location = new Point(0x2db, 0x11b);
            this.SLV6.Name = "SLV6";
            this.SLV6.Size = new Size(0x17, 12);
            this.SLV6.TabIndex = 0xa4;
            this.SLV6.Text = "17%";
            this.SLV5.AutoSize = true;
            this.SLV5.Location = new Point(0x2db, 0x108);
            this.SLV5.Name = "SLV5";
            this.SLV5.Size = new Size(0x17, 12);
            this.SLV5.TabIndex = 0xa3;
            this.SLV5.Text = "17%";
            this.XFMC.AutoSize = true;
            this.XFMC.Location = new Point(0xe0, 360);
            this.XFMC.Name = "XFMC";
            this.XFMC.Size = new Size(0x1d, 12);
            this.XFMC.TabIndex = 0xa6;
            this.XFMC.Text = "XFMC";
            this.XFSH.AutoSize = true;
            this.XFSH.Location = new Point(0xe0, 0x17b);
            this.XFSH.Name = "XFSH";
            this.XFSH.Size = new Size(0x29, 12);
            this.XFSH.TabIndex = 0xa7;
            this.XFSH.Text = "label3";
            this.GFMC.AutoSize = true;
            this.GFMC.Location = new Point(0xe0, 0x5d);
            this.GFMC.Name = "GFMC";
            this.GFMC.Size = new Size(0x2f, 12);
            this.GFMC.TabIndex = 0xa8;
            this.GFMC.Text = "label14";
            this.GFSH.AutoSize = true;
            this.GFSH.Location = new Point(0xe0, 0x6d);
            this.GFSH.Name = "GFSH";
            this.GFSH.Size = new Size(0x2f, 12);
            this.GFSH.TabIndex = 0xa9;
            this.GFSH.Text = "label15";
            this.GFYHZH.AutoSize = true;
            this.GFYHZH.Location = new Point(0xe0, 0x8d);
            this.GFYHZH.Name = "GFYHZH";
            this.GFYHZH.Size = new Size(0x2f, 12);
            this.GFYHZH.TabIndex = 0xab;
            this.GFYHZH.Text = "label15";
            this.GFDZDH.AutoSize = true;
            this.GFDZDH.Location = new Point(0xe0, 0x7d);
            this.GFDZDH.Name = "GFDZDH";
            this.GFDZDH.Size = new Size(0x2f, 12);
            this.GFDZDH.TabIndex = 170;
            this.GFDZDH.Text = "label14";
            this.XFDZDH.AutoSize = true;
            this.XFDZDH.Location = new Point(0xe0, 0x18e);
            this.XFDZDH.Name = "XFDZDH";
            this.XFDZDH.Size = new Size(0x29, 12);
            this.XFDZDH.TabIndex = 0xac;
            this.XFDZDH.Text = "label3";
            this.XFYHZH.AutoSize = true;
            this.XFYHZH.Location = new Point(0xe0, 0x1a1);
            this.XFYHZH.Name = "XFYHZH";
            this.XFYHZH.Size = new Size(0x29, 12);
            this.XFYHZH.TabIndex = 0xad;
            this.XFYHZH.Text = "label3";
            this.BZ.Location = new Point(0x253, 0x171);
            this.BZ.Name = "BZ";
            this.BZ.Size = new Size(0x12a, 60);
            this.BZ.TabIndex = 0xae;
            this.BZ.Text = "label3";
            this.SKR.AutoSize = true;
            this.SKR.Location = new Point(0x98, 0x1c3);
            this.SKR.Name = "SKR";
            this.SKR.Size = new Size(0x29, 12);
            this.SKR.TabIndex = 0xaf;
            this.SKR.Text = "label3";
            this.FHR.AutoSize = true;
            this.FHR.Location = new Point(0x18c, 0x1c3);
            this.FHR.Name = "FHR";
            this.FHR.Size = new Size(0x29, 12);
            this.FHR.TabIndex = 0xb0;
            this.FHR.Text = "label3";
            this.lab_fphm.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.lab_fphm.AutoSize = true;
            this.lab_fphm.BackColor = SystemColors.ButtonHighlight;
            this.lab_fphm.Font = new Font("楷体_GB2312", 15f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.lab_fphm.ForeColor = Color.Maroon;
            this.lab_fphm.Location = new Point(0x2c7, 0x20);
            this.lab_fphm.Name = "lab_fphm";
            this.lab_fphm.Size = new Size(0x61, 20);
            this.lab_fphm.TabIndex = 0xb2;
            this.lab_fphm.Text = "00000000";
            this.lab_fpdm.AutoSize = true;
            this.lab_fpdm.BackColor = SystemColors.ButtonHighlight;
            this.lab_fpdm.Font = new Font("楷体_GB2312", 15f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.lab_fpdm.ForeColor = Color.Maroon;
            this.lab_fpdm.Location = new Point(0x73, 0x20);
            this.lab_fpdm.Name = "lab_fpdm";
            this.lab_fpdm.Size = new Size(0x77, 20);
            this.lab_fpdm.TabIndex = 0xb1;
            this.lab_fpdm.Text = "0000000000";
            this.label3.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.label3.AutoSize = true;
            this.label3.BackColor = SystemColors.ButtonHighlight;
            this.label3.Font = new Font("Script MT Bold", 13f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label3.Location = new Point(0x28d, 30);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x34, 0x16);
            this.label3.TabIndex = 0xb3;
            this.label3.Text = "No：";
            this.invoicePanelLt1.BackColor = SystemColors.ActiveCaptionText;
            this.invoicePanelLt1.BorderStyle = BorderStyle.FixedSingle;
            this.invoicePanelLt1.Dock = DockStyle.Fill;
            this.invoicePanelLt1.Location = new Point(0, 0);
            this.invoicePanelLt1.Name = "invoicePanelLt1";
            this.invoicePanelLt1.Size = new Size(0x3d5, 0x1e3);
            this.invoicePanelLt1.Style = 0;
            this.invoicePanelLt1.TabIndex = 0;
            this.lab_hj_xx.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.lab_hj_xx.AutoSize = true;
            this.lab_hj_xx.BackColor = SystemColors.ControlLightLight;
            this.lab_hj_xx.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lab_hj_xx.Location = new Point(780, 340);
            this.lab_hj_xx.Name = "lab_hj_xx";
            this.lab_hj_xx.Size = new Size(11, 12);
            this.lab_hj_xx.TabIndex = 0x133;
            this.lab_hj_xx.Text = "0";
            this.label2.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.label2.AutoSize = true;
            this.label2.BackColor = SystemColors.ControlLightLight;
            this.label2.Font = new Font("楷体_GB2312", 9f);
            this.label2.Location = new Point(0x2c9, 340);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x35, 12);
            this.label2.TabIndex = 0x132;
            this.label2.Text = "(小写)：";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.Controls.Add(this.lab_hj_xx);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.lab_fphm);
            base.Controls.Add(this.lab_fpdm);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.FHR);
            base.Controls.Add(this.SKR);
            base.Controls.Add(this.BZ);
            base.Controls.Add(this.XFYHZH);
            base.Controls.Add(this.XFDZDH);
            base.Controls.Add(this.GFYHZH);
            base.Controls.Add(this.GFDZDH);
            base.Controls.Add(this.GFSH);
            base.Controls.Add(this.GFMC);
            base.Controls.Add(this.XFSH);
            base.Controls.Add(this.XFMC);
            base.Controls.Add(this.SLV7);
            base.Controls.Add(this.SLV6);
            base.Controls.Add(this.SLV5);
            base.Controls.Add(this.SLV4);
            base.Controls.Add(this.SLV3);
            base.Controls.Add(this.SLV2);
            base.Controls.Add(this.SLV1);
            base.Controls.Add(this.SE7);
            base.Controls.Add(this.SE6);
            base.Controls.Add(this.SE5);
            base.Controls.Add(this.SE4);
            base.Controls.Add(this.SE3);
            base.Controls.Add(this.SE2);
            base.Controls.Add(this.SE1);
            base.Controls.Add(this.JE7);
            base.Controls.Add(this.JE6);
            base.Controls.Add(this.JE5);
            base.Controls.Add(this.JE4);
            base.Controls.Add(this.JE3);
            base.Controls.Add(this.JE2);
            base.Controls.Add(this.JE1);
            base.Controls.Add(this.DJ7);
            base.Controls.Add(this.DJ6);
            base.Controls.Add(this.DJ5);
            base.Controls.Add(this.DJ4);
            base.Controls.Add(this.DJ3);
            base.Controls.Add(this.DJ2);
            base.Controls.Add(this.DJ1);
            base.Controls.Add(this.SL7);
            base.Controls.Add(this.SL6);
            base.Controls.Add(this.SL5);
            base.Controls.Add(this.SL4);
            base.Controls.Add(this.SL3);
            base.Controls.Add(this.SL2);
            base.Controls.Add(this.SL1);
            base.Controls.Add(this.DW3);
            base.Controls.Add(this.DW7);
            base.Controls.Add(this.DW6);
            base.Controls.Add(this.DW5);
            base.Controls.Add(this.DW4);
            base.Controls.Add(this.DW2);
            base.Controls.Add(this.DW1);
            base.Controls.Add(this.GGXH7);
            base.Controls.Add(this.GGXH6);
            base.Controls.Add(this.GGXH5);
            base.Controls.Add(this.GGXH4);
            base.Controls.Add(this.GGXH3);
            base.Controls.Add(this.GGXH2);
            base.Controls.Add(this.GGXH1);
            base.Controls.Add(this.SPMC5);
            base.Controls.Add(this.SPMC7);
            base.Controls.Add(this.SPMC6);
            base.Controls.Add(this.SPMC4);
            base.Controls.Add(this.SPMC3);
            base.Controls.Add(this.SPMC2);
            base.Controls.Add(this.SPMC1);
            base.Controls.Add(this.KPRQ);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.lab_title);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.lab_hj_dx);
            base.Controls.Add(this.label25);
            base.Controls.Add(this.KPR);
            base.Controls.Add(this.label28);
            base.Controls.Add(this.label17);
            base.Controls.Add(this.label27);
            base.Controls.Add(this.label26);
            base.Controls.Add(this.label21);
            base.Controls.Add(this.label20);
            base.Controls.Add(this.label19);
            base.Controls.Add(this.lab_hj_jshj);
            base.Controls.Add(this.label18);
            base.Controls.Add(this.label13);
            base.Controls.Add(this.label16);
            base.Controls.Add(this.label8);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.label9);
            base.Controls.Add(this.label10);
            base.Controls.Add(this.label11);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.TaxTotal);
            base.Controls.Add(this.AmountTotal);
            base.Controls.Add(this.label12);
            base.Controls.Add(this.label24);
            base.Controls.Add(this.label30);
            base.Controls.Add(this.label32);
            base.Controls.Add(this.label29);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.label22);
            base.Controls.Add(this.label31);
            base.Controls.Add(this.label23);
            base.Controls.Add(this.invoicePanelLt1);
            base.Name = "InvoiceLittle";
            base.Size = new Size(0x3d5, 0x1e3);
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private void method_0()
        {
            this.KPRQ.BackColor = SystemColors.ControlLightLight;
            this.KPR.BackColor = SystemColors.ControlLightLight;
            this.TaxTotal.BackColor = SystemColors.ControlLightLight;
            this.AmountTotal.BackColor = SystemColors.ControlLightLight;
            this.XFMC.BackColor = SystemColors.ControlLightLight;
            this.XFSH.BackColor = SystemColors.ControlLightLight;
            this.GFMC.BackColor = SystemColors.ControlLightLight;
            this.GFSH.BackColor = SystemColors.ControlLightLight;
            this.GFYHZH.BackColor = SystemColors.ControlLightLight;
            this.GFDZDH.BackColor = SystemColors.ControlLightLight;
            this.XFDZDH.BackColor = SystemColors.ControlLightLight;
            this.XFYHZH.BackColor = SystemColors.ControlLightLight;
            this.BZ.BackColor = SystemColors.ControlLightLight;
            this.SKR.BackColor = SystemColors.ControlLightLight;
            this.FHR.BackColor = SystemColors.ControlLightLight;
            this.SPMC1.BackColor = SystemColors.ControlLightLight;
            this.SPMC2.BackColor = SystemColors.ControlLightLight;
            this.SPMC3.BackColor = SystemColors.ControlLightLight;
            this.SPMC4.BackColor = SystemColors.ControlLightLight;
            this.SPMC6.BackColor = SystemColors.ControlLightLight;
            this.SPMC7.BackColor = SystemColors.ControlLightLight;
            this.SPMC5.BackColor = SystemColors.ControlLightLight;
            this.GGXH1.BackColor = SystemColors.ControlLightLight;
            this.GGXH2.BackColor = SystemColors.ControlLightLight;
            this.GGXH3.BackColor = SystemColors.ControlLightLight;
            this.GGXH4.BackColor = SystemColors.ControlLightLight;
            this.GGXH7.BackColor = SystemColors.ControlLightLight;
            this.GGXH6.BackColor = SystemColors.ControlLightLight;
            this.GGXH5.BackColor = SystemColors.ControlLightLight;
            this.DW1.BackColor = SystemColors.ControlLightLight;
            this.DW2.BackColor = SystemColors.ControlLightLight;
            this.DW4.BackColor = SystemColors.ControlLightLight;
            this.DW5.BackColor = SystemColors.ControlLightLight;
            this.DW6.BackColor = SystemColors.ControlLightLight;
            this.DW7.BackColor = SystemColors.ControlLightLight;
            this.DW3.BackColor = SystemColors.ControlLightLight;
            this.SL7.BackColor = SystemColors.ControlLightLight;
            this.SL6.BackColor = SystemColors.ControlLightLight;
            this.SL5.BackColor = SystemColors.ControlLightLight;
            this.SL4.BackColor = SystemColors.ControlLightLight;
            this.SL3.BackColor = SystemColors.ControlLightLight;
            this.SL2.BackColor = SystemColors.ControlLightLight;
            this.SL1.BackColor = SystemColors.ControlLightLight;
            this.DJ7.BackColor = SystemColors.ControlLightLight;
            this.DJ6.BackColor = SystemColors.ControlLightLight;
            this.DJ5.BackColor = SystemColors.ControlLightLight;
            this.DJ4.BackColor = SystemColors.ControlLightLight;
            this.DJ3.BackColor = SystemColors.ControlLightLight;
            this.DJ2.BackColor = SystemColors.ControlLightLight;
            this.DJ1.BackColor = SystemColors.ControlLightLight;
            this.JE7.BackColor = SystemColors.ControlLightLight;
            this.JE6.BackColor = SystemColors.ControlLightLight;
            this.JE5.BackColor = SystemColors.ControlLightLight;
            this.JE4.BackColor = SystemColors.ControlLightLight;
            this.JE3.BackColor = SystemColors.ControlLightLight;
            this.JE2.BackColor = SystemColors.ControlLightLight;
            this.JE1.BackColor = SystemColors.ControlLightLight;
            this.SE7.BackColor = SystemColors.ControlLightLight;
            this.SE6.BackColor = SystemColors.ControlLightLight;
            this.SE5.BackColor = SystemColors.ControlLightLight;
            this.SE4.BackColor = SystemColors.ControlLightLight;
            this.SE3.BackColor = SystemColors.ControlLightLight;
            this.SE2.BackColor = SystemColors.ControlLightLight;
            this.SE1.BackColor = SystemColors.ControlLightLight;
            this.SLV1.BackColor = SystemColors.ControlLightLight;
            this.SLV2.BackColor = SystemColors.ControlLightLight;
            this.SLV4.BackColor = SystemColors.ControlLightLight;
            this.SLV3.BackColor = SystemColors.ControlLightLight;
            this.SLV7.BackColor = SystemColors.ControlLightLight;
            this.SLV6.BackColor = SystemColors.ControlLightLight;
            this.SLV5.BackColor = SystemColors.ControlLightLight;
            this.KPRQ.ForeColor = Color.Blue;
            this.KPR.ForeColor = Color.Blue;
            this.TaxTotal.ForeColor = Color.Blue;
            this.AmountTotal.ForeColor = Color.Blue;
            this.lab_hj_xx.ForeColor = Color.Blue;
            this.lab_hj_dx.ForeColor = Color.Blue;
            this.XFMC.ForeColor = Color.Blue;
            this.XFSH.ForeColor = Color.Blue;
            this.GFMC.ForeColor = Color.Blue;
            this.GFSH.ForeColor = Color.Blue;
            this.GFYHZH.ForeColor = Color.Blue;
            this.GFDZDH.ForeColor = Color.Blue;
            this.XFDZDH.ForeColor = Color.Blue;
            this.XFYHZH.ForeColor = Color.Blue;
            this.BZ.ForeColor = Color.Blue;
            this.SKR.ForeColor = Color.Blue;
            this.FHR.ForeColor = Color.Blue;
            this.SPMC1.ForeColor = Color.Blue;
            this.SPMC2.ForeColor = Color.Blue;
            this.SPMC3.ForeColor = Color.Blue;
            this.SPMC4.ForeColor = Color.Blue;
            this.SPMC6.ForeColor = Color.Blue;
            this.SPMC7.ForeColor = Color.Blue;
            this.SPMC5.ForeColor = Color.Blue;
            this.GGXH1.ForeColor = Color.Blue;
            this.GGXH2.ForeColor = Color.Blue;
            this.GGXH3.ForeColor = Color.Blue;
            this.GGXH4.ForeColor = Color.Blue;
            this.GGXH7.ForeColor = Color.Blue;
            this.GGXH6.ForeColor = Color.Blue;
            this.GGXH5.ForeColor = Color.Blue;
            this.DW1.ForeColor = Color.Blue;
            this.DW2.ForeColor = Color.Blue;
            this.DW4.ForeColor = Color.Blue;
            this.DW5.ForeColor = Color.Blue;
            this.DW6.ForeColor = Color.Blue;
            this.DW7.ForeColor = Color.Blue;
            this.DW3.ForeColor = Color.Blue;
            this.SL7.ForeColor = Color.Blue;
            this.SL6.ForeColor = Color.Blue;
            this.SL5.ForeColor = Color.Blue;
            this.SL4.ForeColor = Color.Blue;
            this.SL3.ForeColor = Color.Blue;
            this.SL2.ForeColor = Color.Blue;
            this.SL1.ForeColor = Color.Blue;
            this.DJ7.ForeColor = Color.Blue;
            this.DJ6.ForeColor = Color.Blue;
            this.DJ5.ForeColor = Color.Blue;
            this.DJ4.ForeColor = Color.Blue;
            this.DJ3.ForeColor = Color.Blue;
            this.DJ2.ForeColor = Color.Blue;
            this.DJ1.ForeColor = Color.Blue;
            this.JE7.ForeColor = Color.Blue;
            this.JE6.ForeColor = Color.Blue;
            this.JE5.ForeColor = Color.Blue;
            this.JE4.ForeColor = Color.Blue;
            this.JE3.ForeColor = Color.Blue;
            this.JE2.ForeColor = Color.Blue;
            this.JE1.ForeColor = Color.Blue;
            this.SE7.ForeColor = Color.Blue;
            this.SE6.ForeColor = Color.Blue;
            this.SE5.ForeColor = Color.Blue;
            this.SE4.ForeColor = Color.Blue;
            this.SE3.ForeColor = Color.Blue;
            this.SE2.ForeColor = Color.Blue;
            this.SE1.ForeColor = Color.Blue;
            this.SLV1.ForeColor = Color.Blue;
            this.SLV2.ForeColor = Color.Blue;
            this.SLV4.ForeColor = Color.Blue;
            this.SLV3.ForeColor = Color.Blue;
            this.SLV7.ForeColor = Color.Blue;
            this.SLV6.ForeColor = Color.Blue;
            this.SLV5.ForeColor = Color.Blue;
        }

        private void method_1()
        {
            this.KPRQ.Text = "";
            this.KPR.Text = "";
            this.TaxTotal.Text = "";
            this.AmountTotal.Text = "";
            this.XFMC.Text = "";
            this.XFSH.Text = "";
            this.GFMC.Text = "";
            this.GFSH.Text = "";
            this.GFYHZH.Text = "";
            this.GFDZDH.Text = "";
            this.XFDZDH.Text = "";
            this.XFYHZH.Text = "";
            this.BZ.Text = "";
            this.SKR.Text = "";
            this.FHR.Text = "";
            this.SPMC1.Text = "";
            this.SPMC2.Text = "";
            this.SPMC3.Text = "";
            this.SPMC4.Text = "";
            this.SPMC6.Text = "";
            this.SPMC7.Text = "";
            this.SPMC5.Text = "";
            this.GGXH1.Text = "";
            this.GGXH2.Text = "";
            this.GGXH3.Text = "";
            this.GGXH4.Text = "";
            this.GGXH7.Text = "";
            this.GGXH6.Text = "";
            this.GGXH5.Text = "";
            this.DW1.Text = "";
            this.DW2.Text = "";
            this.DW4.Text = "";
            this.DW5.Text = "";
            this.DW6.Text = "";
            this.DW7.Text = "";
            this.DW3.Text = "";
            this.SL7.Text = "";
            this.SL6.Text = "";
            this.SL5.Text = "";
            this.SL4.Text = "";
            this.SL3.Text = "";
            this.SL2.Text = "";
            this.SL1.Text = "";
            this.DJ7.Text = "";
            this.DJ6.Text = "";
            this.DJ5.Text = "";
            this.DJ4.Text = "";
            this.DJ3.Text = "";
            this.DJ2.Text = "";
            this.DJ1.Text = "";
            this.JE7.Text = "";
            this.JE6.Text = "";
            this.JE5.Text = "";
            this.JE4.Text = "";
            this.JE3.Text = "";
            this.JE2.Text = "";
            this.JE1.Text = "";
            this.SE7.Text = "";
            this.SE6.Text = "";
            this.SE5.Text = "";
            this.SE4.Text = "";
            this.SE3.Text = "";
            this.SE2.Text = "";
            this.SE1.Text = "";
            this.SLV1.Text = "";
            this.SLV2.Text = "";
            this.SLV4.Text = "";
            this.SLV3.Text = "";
            this.SLV7.Text = "";
            this.SLV6.Text = "";
            this.SLV5.Text = "";
        }
    }
}

