namespace Aisino.Fwkp.Wbjk
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential, Size=1)]
    internal struct PARAMS
    {
        internal static string ZERO;
        internal static int NSSBH_MAX_LEN;
        internal static int XFMC_MAX_LEN;
        internal static int GFMC_MAX_LEN;
        internal static int GFDZDH_MAX_LEN;
        internal static int GFYHZH_MAX_LEN;
        internal static int FYXM_MAX_LINE;
        internal static int JQBH_MAX_LEN;
        internal static int SHRMC_MAX_LEN;
        internal static int FHRMC_MAX_LEN;
        internal static int QYD_JY_DDD_MAX_LEN;
        internal static int YSHWXX_MAX_LEN;
        internal static int CZCH_MAX_LEN;
        internal static int CCDW_MAX_LEN;
        internal static int SFZHM_ZZJGDM_MAX_LEN;
        internal static int CLLX_MAX_LEN;
        internal static int CPXH_MAX_LEN;
        internal static int CD_MAX_LEN;
        internal static int HGZH_MAX_LEN;
        internal static int JKZMSH_MAX_LEN;
        internal static int SJDH_MAX_LEN;
        internal static int FDJHM_MAX_LEN;
        internal static int CLSBDM_CJHM_MAX_LEN;
        internal static int SCCJ_MAX_LEN;
        internal static int DH_MAX_LEN;
        internal static int DZ_MAX_LEN;
        internal static int KHYH_MAX_LEN;
        internal static int ZH_MAX_LEN;
        internal static int DW_MAX_LEN;
        internal static int XCRS_MAX_LEN;
        internal static int XFDZDH_MAX_LEN;
        internal static int XFYHZH_MAX_LEN;
        internal static int BZ_MAX_LEN;
        internal static int KPR_MAX_LEN;
        internal static int SKR_MAX_LEN;
        internal static int FHR_MAX_LEN;
        internal static int SPMC_MAX_LEN;
        internal static int HY_FYXM_MAX_LEM_10;
        internal static int HY_FYXM_LINE_FLAG;
        internal static int JLDW_MAX_LEN;
        internal static int GGXH_MAX_LEN;
        internal static string HJ_JE_ERR;
        internal static string JE_ERR;
        internal static string SE_ERR;
        internal static string JE_SE_ERR;
        internal static string JE_HJ_ERR;
        internal static string SE_HJ_ERR;
        internal static int DJ_MAX_DECIMALS;
        internal static int DJ_MAX_LEN;
        internal static int SL_MAX_DECIMALS;
        internal static int SL_MAX_LEN;
        internal static int JE_DECIMALS;
        internal static int JE_MAX_LEN;
        internal static int SE_MAX_LEN;
        internal static int ZKLV_DECIMALS;
        internal static int SLV_DECIMALS;
        internal static string XHQD_SPMC;
        internal static string XHQD_SPMC_RED;
        internal static string QD_YJHJ_MC;
        internal static string QD_ZKHJ_MC;
        public static Dictionary<ZYFP_LX, string> YPLX_SPMC_TAIL;
        internal static string SPMC_QD;
        internal static string XT_JLDW_1;
        internal static string XT_JLDW_2;
        internal static string YPLX_JLDW;
        internal static List<string> ZYFP_SLV_LIST;
        internal static List<string> ZYFP_SLV_HYSY_LIST;
        internal static List<string> HYFP_SLV_LIST;
        internal static List<string> JDC_SLV_LIST;
        internal static List<string> PTFP_SLV_LIST;
        internal static string KSLV_CHECK_MAX;
        internal static string KSLV_CHECK_MIN;
        static PARAMS()
        {
            ZERO = "0.00";
            NSSBH_MAX_LEN = 20;
            XFMC_MAX_LEN = 100;
            GFMC_MAX_LEN = 100;
            GFDZDH_MAX_LEN = 100;
            GFYHZH_MAX_LEN = 100;
            FYXM_MAX_LINE = 0x12;
            JQBH_MAX_LEN = 12;
            SHRMC_MAX_LEN = 80;
            FHRMC_MAX_LEN = 80;
            QYD_JY_DDD_MAX_LEN = 90;
            YSHWXX_MAX_LEN = 200;
            CZCH_MAX_LEN = 30;
            CCDW_MAX_LEN = 8;
            SFZHM_ZZJGDM_MAX_LEN = 20;
            CLLX_MAX_LEN = 40;
            CPXH_MAX_LEN = 60;
            CD_MAX_LEN = 0x20;
            HGZH_MAX_LEN = 50;
            JKZMSH_MAX_LEN = 0x24;
            SJDH_MAX_LEN = 0x20;
            FDJHM_MAX_LEN = 50;
            CLSBDM_CJHM_MAX_LEN = 0x17;
            SCCJ_MAX_LEN = 80;
            DH_MAX_LEN = 40;
            DZ_MAX_LEN = 80;
            KHYH_MAX_LEN = 80;
            ZH_MAX_LEN = 40;
            DW_MAX_LEN = 8;
            XCRS_MAX_LEN = 12;
            XFDZDH_MAX_LEN = 100;
            XFYHZH_MAX_LEN = 100;
            BZ_MAX_LEN = 230;
            KPR_MAX_LEN = 8;
            SKR_MAX_LEN = 8;
            FHR_MAX_LEN = 8;
            SPMC_MAX_LEN = 0x5c;
            HY_FYXM_MAX_LEM_10 = 12;
            HY_FYXM_LINE_FLAG = 10;
            JLDW_MAX_LEN = 0x16;
            GGXH_MAX_LEN = 40;
            HJ_JE_ERR = "0.01";
            JE_ERR = "0.01";
            SE_ERR = "0.06";
            JE_SE_ERR = "-1";
            JE_HJ_ERR = "1.27";
            SE_HJ_ERR = "0.625";
            DJ_MAX_DECIMALS = 15;
            DJ_MAX_LEN = 0x15;
            SL_MAX_DECIMALS = 15;
            SL_MAX_LEN = 0x15;
            JE_DECIMALS = 2;
            JE_MAX_LEN = 0x12;
            SE_MAX_LEN = 0x12;
            ZKLV_DECIMALS = 5;
            SLV_DECIMALS = 2;
            XHQD_SPMC = "(详见销货清单)";
            XHQD_SPMC_RED = "详见对应正数发票及清单";
            QD_YJHJ_MC = "原价合计";
            QD_ZKHJ_MC = "折扣额合计";
            Dictionary<ZYFP_LX, string> dictionary = new Dictionary<ZYFP_LX, string>();
            dictionary.Add(2, "(石脑油)");
            dictionary.Add(3, "(石脑油DDZG)");
            dictionary.Add(4, "(燃料油)");
            dictionary.Add(5, "(燃料油DDZG)");
            YPLX_SPMC_TAIL = dictionary;
            SPMC_QD = "清单";
            XT_JLDW_1 = "吨";
            XT_JLDW_2 = "公斤";
            YPLX_JLDW = "吨";
            ZYFP_SLV_LIST = new List<string>();
            ZYFP_SLV_HYSY_LIST = new List<string>();
            HYFP_SLV_LIST = new List<string>();
            JDC_SLV_LIST = new List<string>();
            PTFP_SLV_LIST = new List<string>();
            KSLV_CHECK_MAX = "0.25";
            KSLV_CHECK_MIN = "0.00";
        }
    }
}

