// Assembly Aisino.FTaxBase, Version 2.1.30.419

[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyTitle("税控发票开票软件（金税盘版）")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("航天信息股份有限公司")]
[assembly: System.Reflection.AssemblyProduct("税控发票开票软件（金税盘版）")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 航天信息股份有限公司 2014-2015")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("054ac435-15b0-47f6-8fd5-62788a81cc7b")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.30.419")]
[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyKeyName("")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

